// Code generated by generate_go_msgs.sh — DO NOT EDIT.
package nav

import (
	"github.com/mowglinext/mowglinext/pkg/msgs/geometry"
)

// MapMetaData matches nav_msgs/msg/MapMetaData.
type MapMetaData struct {
	MapLoadTime               geometry.Stamp                 `json:"map_load_time"`
	Resolution                float32                        `json:"resolution"`
	Width                     uint32                         `json:"width"`
	Height                    uint32                         `json:"height"`
	Origin                    geometry.Pose                  `json:"origin"`
}

// OccupancyGrid matches nav_msgs/msg/OccupancyGrid.
type OccupancyGrid struct {
	Header                    geometry.Header                `json:"header"`
	Info                      MapMetaData                    `json:"info"`
	Data                      []int8                         `json:"data"`
}

// Odometry matches nav_msgs/msg/Odometry.
type Odometry struct {
	Header                    geometry.Header                `json:"header"`
	ChildFrameId              string                         `json:"child_frame_id"`
	Pose                      geometry.PoseWithCovariance    `json:"pose"`
	Twist                     geometry.TwistWithCovariance   `json:"twist"`
}

// Path matches nav_msgs/msg/Path.
type Path struct {
	Header                    geometry.Header                `json:"header"`
	Poses                     []geometry.PoseStamped         `json:"poses"`
}

