blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://mowgli.garden
    about: Check the docs before opening an issue
  - name: Discussions
    url: https://github.com/mowglinext/mowglinext/discussions
    about: Ask questions and share ideas
