#ifndef _ROS_mower_msgs_AbsolutePose_h
#define _ROS_mower_msgs_AbsolutePose_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"
#include "geometry_msgs/PoseWithCovariance.h"
#include "geometry_msgs/Vector3.h"
#include "std_msgs/Header.h"

namespace mower_msgs
{

  class AbsolutePose : public ros::Msg
  {
    public:
      typedef std_msgs::Header _header_type;
      _header_type header;
      typedef uint32_t _sensor_stamp_type;
      _sensor_stamp_type sensor_stamp;
      typedef uint32_t _received_stamp_type;
      _received_stamp_type received_stamp;
      typedef uint8_t _source_type;
      _source_type source;
      typedef uint16_t _flags_type;
      _flags_type flags;
      typedef uint8_t _orientation_valid_type;
      _orientation_valid_type orientation_valid;
      typedef uint8_t _motion_vector_valid_type;
      _motion_vector_valid_type motion_vector_valid;
      typedef float _position_accuracy_type;
      _position_accuracy_type position_accuracy;
      typedef float _orientation_accuracy_type;
      _orientation_accuracy_type orientation_accuracy;
      typedef geometry_msgs::PoseWithCovariance _pose_type;
      _pose_type pose;
      typedef geometry_msgs::Vector3 _motion_vector_type;
      _motion_vector_type motion_vector;
      typedef double _vehicle_heading_type;
      _vehicle_heading_type vehicle_heading;
      typedef double _motion_heading_type;
      _motion_heading_type motion_heading;
      enum { SOURCE_GPS = 1 };
      enum { SOURCE_LIGHTHOUSE = 2 };
      enum { SOURCE_SENSOR_FUSION = 100 };
      enum { FLAG_GPS_RTK = 1 };
      enum { FLAG_GPS_RTK_FIXED = 2 };
      enum { FLAG_GPS_RTK_FLOAT = 4 };
      enum { FLAG_GPS_DEAD_RECKONING = 8 };
      enum { FLAG_SENSOR_FUSION_RECENT_ABSOLUTE_POSE = 1 };
      enum { FLAG_SENSOR_FUSION_DEAD_RECKONING = 8 };

    AbsolutePose():
      header(),
      sensor_stamp(0),
      received_stamp(0),
      source(0),
      flags(0),
      orientation_valid(0),
      motion_vector_valid(0),
      position_accuracy(0),
      orientation_accuracy(0),
      pose(),
      motion_vector(),
      vehicle_heading(0),
      motion_heading(0)
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      offset += this->header.serialize(outbuffer + offset);
      union {
        uint32_t real;
        uint32_t base;
      } u_sensor_stamp;
      u_sensor_stamp.real = this->sensor_stamp;
      *(outbuffer + offset + 0) = (u_sensor_stamp.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_sensor_stamp.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_sensor_stamp.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_sensor_stamp.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->sensor_stamp);
      union {
        uint32_t real;
        uint32_t base;
      } u_received_stamp;
      u_received_stamp.real = this->received_stamp;
      *(outbuffer + offset + 0) = (u_received_stamp.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_received_stamp.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_received_stamp.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_received_stamp.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->received_stamp);
      *(outbuffer + offset + 0) = (this->source >> (8 * 0)) & 0xFF;
      offset += sizeof(this->source);
      union {
        uint16_t real;
        uint16_t base;
      } u_flags;
      u_flags.real = this->flags;
      *(outbuffer + offset + 0) = (u_flags.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_flags.base >> (8 * 1)) & 0xFF;
      offset += sizeof(this->flags);
      *(outbuffer + offset + 0) = (this->orientation_valid >> (8 * 0)) & 0xFF;
      offset += sizeof(this->orientation_valid);
      *(outbuffer + offset + 0) = (this->motion_vector_valid >> (8 * 0)) & 0xFF;
      offset += sizeof(this->motion_vector_valid);
      union {
        float real;
        uint32_t base;
      } u_position_accuracy;
      u_position_accuracy.real = this->position_accuracy;
      *(outbuffer + offset + 0) = (u_position_accuracy.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_position_accuracy.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_position_accuracy.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_position_accuracy.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->position_accuracy);
      union {
        float real;
        uint32_t base;
      } u_orientation_accuracy;
      u_orientation_accuracy.real = this->orientation_accuracy;
      *(outbuffer + offset + 0) = (u_orientation_accuracy.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_orientation_accuracy.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_orientation_accuracy.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_orientation_accuracy.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->orientation_accuracy);
      offset += this->pose.serialize(outbuffer + offset);
      offset += this->motion_vector.serialize(outbuffer + offset);
      union {
        double real;
        uint64_t base;
      } u_vehicle_heading;
      u_vehicle_heading.real = this->vehicle_heading;
      *(outbuffer + offset + 0) = (u_vehicle_heading.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_vehicle_heading.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_vehicle_heading.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_vehicle_heading.base >> (8 * 3)) & 0xFF;
      *(outbuffer + offset + 4) = (u_vehicle_heading.base >> (8 * 4)) & 0xFF;
      *(outbuffer + offset + 5) = (u_vehicle_heading.base >> (8 * 5)) & 0xFF;
      *(outbuffer + offset + 6) = (u_vehicle_heading.base >> (8 * 6)) & 0xFF;
      *(outbuffer + offset + 7) = (u_vehicle_heading.base >> (8 * 7)) & 0xFF;
      offset += sizeof(this->vehicle_heading);
      union {
        double real;
        uint64_t base;
      } u_motion_heading;
      u_motion_heading.real = this->motion_heading;
      *(outbuffer + offset + 0) = (u_motion_heading.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_motion_heading.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_motion_heading.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_motion_heading.base >> (8 * 3)) & 0xFF;
      *(outbuffer + offset + 4) = (u_motion_heading.base >> (8 * 4)) & 0xFF;
      *(outbuffer + offset + 5) = (u_motion_heading.base >> (8 * 5)) & 0xFF;
      *(outbuffer + offset + 6) = (u_motion_heading.base >> (8 * 6)) & 0xFF;
      *(outbuffer + offset + 7) = (u_motion_heading.base >> (8 * 7)) & 0xFF;
      offset += sizeof(this->motion_heading);
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      offset += this->header.deserialize(inbuffer + offset);
      union {
        uint32_t real;
        uint32_t base;
      } u_sensor_stamp;
      u_sensor_stamp.base = 0;
      u_sensor_stamp.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_sensor_stamp.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_sensor_stamp.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_sensor_stamp.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->sensor_stamp = u_sensor_stamp.real;
      offset += sizeof(this->sensor_stamp);
      union {
        uint32_t real;
        uint32_t base;
      } u_received_stamp;
      u_received_stamp.base = 0;
      u_received_stamp.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_received_stamp.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_received_stamp.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_received_stamp.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->received_stamp = u_received_stamp.real;
      offset += sizeof(this->received_stamp);
      this->source =  ((uint8_t) (*(inbuffer + offset)));
      offset += sizeof(this->source);
      union {
        uint16_t real;
        uint16_t base;
      } u_flags;
      u_flags.base = 0;
      u_flags.base |= ((uint16_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_flags.base |= ((uint16_t) (*(inbuffer + offset + 1))) << (8 * 1);
      this->flags = u_flags.real;
      offset += sizeof(this->flags);
      this->orientation_valid =  ((uint8_t) (*(inbuffer + offset)));
      offset += sizeof(this->orientation_valid);
      this->motion_vector_valid =  ((uint8_t) (*(inbuffer + offset)));
      offset += sizeof(this->motion_vector_valid);
      union {
        float real;
        uint32_t base;
      } u_position_accuracy;
      u_position_accuracy.base = 0;
      u_position_accuracy.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_position_accuracy.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_position_accuracy.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_position_accuracy.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->position_accuracy = u_position_accuracy.real;
      offset += sizeof(this->position_accuracy);
      union {
        float real;
        uint32_t base;
      } u_orientation_accuracy;
      u_orientation_accuracy.base = 0;
      u_orientation_accuracy.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_orientation_accuracy.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_orientation_accuracy.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_orientation_accuracy.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->orientation_accuracy = u_orientation_accuracy.real;
      offset += sizeof(this->orientation_accuracy);
      offset += this->pose.deserialize(inbuffer + offset);
      offset += this->motion_vector.deserialize(inbuffer + offset);
      union {
        double real;
        uint64_t base;
      } u_vehicle_heading;
      u_vehicle_heading.base = 0;
      u_vehicle_heading.base |= ((uint64_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_vehicle_heading.base |= ((uint64_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_vehicle_heading.base |= ((uint64_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_vehicle_heading.base |= ((uint64_t) (*(inbuffer + offset + 3))) << (8 * 3);
      u_vehicle_heading.base |= ((uint64_t) (*(inbuffer + offset + 4))) << (8 * 4);
      u_vehicle_heading.base |= ((uint64_t) (*(inbuffer + offset + 5))) << (8 * 5);
      u_vehicle_heading.base |= ((uint64_t) (*(inbuffer + offset + 6))) << (8 * 6);
      u_vehicle_heading.base |= ((uint64_t) (*(inbuffer + offset + 7))) << (8 * 7);
      this->vehicle_heading = u_vehicle_heading.real;
      offset += sizeof(this->vehicle_heading);
      union {
        double real;
        uint64_t base;
      } u_motion_heading;
      u_motion_heading.base = 0;
      u_motion_heading.base |= ((uint64_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_motion_heading.base |= ((uint64_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_motion_heading.base |= ((uint64_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_motion_heading.base |= ((uint64_t) (*(inbuffer + offset + 3))) << (8 * 3);
      u_motion_heading.base |= ((uint64_t) (*(inbuffer + offset + 4))) << (8 * 4);
      u_motion_heading.base |= ((uint64_t) (*(inbuffer + offset + 5))) << (8 * 5);
      u_motion_heading.base |= ((uint64_t) (*(inbuffer + offset + 6))) << (8 * 6);
      u_motion_heading.base |= ((uint64_t) (*(inbuffer + offset + 7))) << (8 * 7);
      this->motion_heading = u_motion_heading.real;
      offset += sizeof(this->motion_heading);
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/AbsolutePose"; };
    virtual const char * getMD5() override { return "e7200172a9fe92c28560e51a1eb65308"; };

  };

}
#endif
