#ifndef _ROS_mower_msgs_CoveragePath_h
#define _ROS_mower_msgs_CoveragePath_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"
#include "nav_msgs/Path.h"

namespace mower_msgs
{

  class CoveragePath : public ros::Msg
  {
    public:
      typedef bool _is_outline_type;
      _is_outline_type is_outline;
      typedef nav_msgs::Path _path_type;
      _path_type path;

    CoveragePath():
      is_outline(0),
      path()
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      union {
        bool real;
        uint8_t base;
      } u_is_outline;
      u_is_outline.real = this->is_outline;
      *(outbuffer + offset + 0) = (u_is_outline.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->is_outline);
      offset += this->path.serialize(outbuffer + offset);
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      union {
        bool real;
        uint8_t base;
      } u_is_outline;
      u_is_outline.base = 0;
      u_is_outline.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->is_outline = u_is_outline.real;
      offset += sizeof(this->is_outline);
      offset += this->path.deserialize(inbuffer + offset);
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/CoveragePath"; };
    virtual const char * getMD5() override { return "ab99ba7b57b95f1a96eff7f3e9665778"; };

  };

}
#endif
