#ifndef _ROS_mower_msgs_CoveragePlanPreview_h
#define _ROS_mower_msgs_CoveragePlanPreview_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"
#include "std_msgs/Header.h"

namespace mower_msgs
{

  class CoveragePlanPreview : public ros::Msg
  {
    public:
      typedef std_msgs::Header _header_type;
      _header_type header;
      uint32_t xy_length;
      typedef float _xy_type;
      _xy_type st_xy;
      _xy_type * xy;
      uint32_t subpath_offsets_length;
      typedef uint32_t _subpath_offsets_type;
      _subpath_offsets_type st_subpath_offsets;
      _subpath_offsets_type * subpath_offsets;

    CoveragePlanPreview():
      header(),
      xy_length(0), st_xy(), xy(nullptr),
      subpath_offsets_length(0), st_subpath_offsets(), subpath_offsets(nullptr)
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      offset += this->header.serialize(outbuffer + offset);
      *(outbuffer + offset + 0) = (this->xy_length >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (this->xy_length >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (this->xy_length >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (this->xy_length >> (8 * 3)) & 0xFF;
      offset += sizeof(this->xy_length);
      for( uint32_t i = 0; i < xy_length; i++){
        union {
          float real;
          uint32_t base;
        } u_xy[i];
        u_xy[i].real = this->xy[i];
        *(outbuffer + offset + 0) = (u_xy[i].base >> (8 * 0)) & 0xFF;
        *(outbuffer + offset + 1) = (u_xy[i].base >> (8 * 1)) & 0xFF;
        *(outbuffer + offset + 2) = (u_xy[i].base >> (8 * 2)) & 0xFF;
        *(outbuffer + offset + 3) = (u_xy[i].base >> (8 * 3)) & 0xFF;
        offset += sizeof(this->xy[i]);
      }
      *(outbuffer + offset + 0) = (this->subpath_offsets_length >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (this->subpath_offsets_length >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (this->subpath_offsets_length >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (this->subpath_offsets_length >> (8 * 3)) & 0xFF;
      offset += sizeof(this->subpath_offsets_length);
      for( uint32_t i = 0; i < subpath_offsets_length; i++){
        union {
          uint32_t real;
          uint32_t base;
        } u_subpath_offsets[i];
        u_subpath_offsets[i].real = this->subpath_offsets[i];
        *(outbuffer + offset + 0) = (u_subpath_offsets[i].base >> (8 * 0)) & 0xFF;
        *(outbuffer + offset + 1) = (u_subpath_offsets[i].base >> (8 * 1)) & 0xFF;
        *(outbuffer + offset + 2) = (u_subpath_offsets[i].base >> (8 * 2)) & 0xFF;
        *(outbuffer + offset + 3) = (u_subpath_offsets[i].base >> (8 * 3)) & 0xFF;
        offset += sizeof(this->subpath_offsets[i]);
      }
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      offset += this->header.deserialize(inbuffer + offset);
      uint32_t xy_lengthT = ((uint32_t) (*(inbuffer + offset)));
      xy_lengthT |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      xy_lengthT |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      xy_lengthT |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      offset += sizeof(this->xy_length);
      if(xy_lengthT > xy_length)
        this->xy = (float*)realloc(this->xy, xy_lengthT * sizeof(float));
      xy_length = xy_lengthT;
      for( uint32_t i = 0; i < xy_length; i++){
        union {
          float real;
          uint32_t base;
        } u_xy[i];
        u_xy[i].base = 0;
        u_xy[i].base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
        u_xy[i].base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
        u_xy[i].base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
        u_xy[i].base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
        this->xy[i] = u_xy[i].real;
        offset += sizeof(this->xy[i]);
      }
      uint32_t subpath_offsets_lengthT = ((uint32_t) (*(inbuffer + offset)));
      subpath_offsets_lengthT |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      subpath_offsets_lengthT |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      subpath_offsets_lengthT |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      offset += sizeof(this->subpath_offsets_length);
      if(subpath_offsets_lengthT > subpath_offsets_length)
        this->subpath_offsets = (uint32_t*)realloc(this->subpath_offsets, subpath_offsets_lengthT * sizeof(uint32_t));
      subpath_offsets_length = subpath_offsets_lengthT;
      for( uint32_t i = 0; i < subpath_offsets_length; i++){
        union {
          uint32_t real;
          uint32_t base;
        } u_subpath_offsets[i];
        u_subpath_offsets[i].base = 0;
        u_subpath_offsets[i].base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
        u_subpath_offsets[i].base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
        u_subpath_offsets[i].base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
        u_subpath_offsets[i].base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
        this->subpath_offsets[i] = u_subpath_offsets[i].real;
        offset += sizeof(this->subpath_offsets[i]);
      }
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/CoveragePlanPreview"; };
    virtual const char * getMD5() override { return "393a1b0a5a31ac5638a63c1c00a3ed87"; };

  };

}
#endif
