#ifndef _ROS_mower_msgs_CoverageSession_h
#define _ROS_mower_msgs_CoverageSession_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"

namespace mower_msgs
{

  class CoverageSession : public ros::Msg
  {
    public:
      typedef bool _session_active_type;
      _session_active_type session_active;
      typedef int16_t _current_area_type;
      _current_area_type current_area;
      uint32_t completed_areas_length;
      typedef uint32_t _completed_areas_type;
      _completed_areas_type st_completed_areas;
      _completed_areas_type * completed_areas;
      uint32_t attempted_areas_length;
      typedef uint32_t _attempted_areas_type;
      _attempted_areas_type st_attempted_areas;
      _attempted_areas_type * attempted_areas;
      uint32_t excluded_areas_length;
      typedef uint32_t _excluded_areas_type;
      _excluded_areas_type st_excluded_areas;
      _excluded_areas_type * excluded_areas;

    CoverageSession():
      session_active(0),
      current_area(0),
      completed_areas_length(0), st_completed_areas(), completed_areas(nullptr),
      attempted_areas_length(0), st_attempted_areas(), attempted_areas(nullptr),
      excluded_areas_length(0), st_excluded_areas(), excluded_areas(nullptr)
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      union {
        bool real;
        uint8_t base;
      } u_session_active;
      u_session_active.real = this->session_active;
      *(outbuffer + offset + 0) = (u_session_active.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->session_active);
      union {
        int16_t real;
        uint16_t base;
      } u_current_area;
      u_current_area.real = this->current_area;
      *(outbuffer + offset + 0) = (u_current_area.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_current_area.base >> (8 * 1)) & 0xFF;
      offset += sizeof(this->current_area);
      *(outbuffer + offset + 0) = (this->completed_areas_length >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (this->completed_areas_length >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (this->completed_areas_length >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (this->completed_areas_length >> (8 * 3)) & 0xFF;
      offset += sizeof(this->completed_areas_length);
      for( uint32_t i = 0; i < completed_areas_length; i++){
        union {
          uint32_t real;
          uint32_t base;
        } u_completed_areas[i];
        u_completed_areas[i].real = this->completed_areas[i];
        *(outbuffer + offset + 0) = (u_completed_areas[i].base >> (8 * 0)) & 0xFF;
        *(outbuffer + offset + 1) = (u_completed_areas[i].base >> (8 * 1)) & 0xFF;
        *(outbuffer + offset + 2) = (u_completed_areas[i].base >> (8 * 2)) & 0xFF;
        *(outbuffer + offset + 3) = (u_completed_areas[i].base >> (8 * 3)) & 0xFF;
        offset += sizeof(this->completed_areas[i]);
      }
      *(outbuffer + offset + 0) = (this->attempted_areas_length >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (this->attempted_areas_length >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (this->attempted_areas_length >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (this->attempted_areas_length >> (8 * 3)) & 0xFF;
      offset += sizeof(this->attempted_areas_length);
      for( uint32_t i = 0; i < attempted_areas_length; i++){
        union {
          uint32_t real;
          uint32_t base;
        } u_attempted_areas[i];
        u_attempted_areas[i].real = this->attempted_areas[i];
        *(outbuffer + offset + 0) = (u_attempted_areas[i].base >> (8 * 0)) & 0xFF;
        *(outbuffer + offset + 1) = (u_attempted_areas[i].base >> (8 * 1)) & 0xFF;
        *(outbuffer + offset + 2) = (u_attempted_areas[i].base >> (8 * 2)) & 0xFF;
        *(outbuffer + offset + 3) = (u_attempted_areas[i].base >> (8 * 3)) & 0xFF;
        offset += sizeof(this->attempted_areas[i]);
      }
      *(outbuffer + offset + 0) = (this->excluded_areas_length >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (this->excluded_areas_length >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (this->excluded_areas_length >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (this->excluded_areas_length >> (8 * 3)) & 0xFF;
      offset += sizeof(this->excluded_areas_length);
      for( uint32_t i = 0; i < excluded_areas_length; i++){
        union {
          uint32_t real;
          uint32_t base;
        } u_excluded_areas[i];
        u_excluded_areas[i].real = this->excluded_areas[i];
        *(outbuffer + offset + 0) = (u_excluded_areas[i].base >> (8 * 0)) & 0xFF;
        *(outbuffer + offset + 1) = (u_excluded_areas[i].base >> (8 * 1)) & 0xFF;
        *(outbuffer + offset + 2) = (u_excluded_areas[i].base >> (8 * 2)) & 0xFF;
        *(outbuffer + offset + 3) = (u_excluded_areas[i].base >> (8 * 3)) & 0xFF;
        offset += sizeof(this->excluded_areas[i]);
      }
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      union {
        bool real;
        uint8_t base;
      } u_session_active;
      u_session_active.base = 0;
      u_session_active.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->session_active = u_session_active.real;
      offset += sizeof(this->session_active);
      union {
        int16_t real;
        uint16_t base;
      } u_current_area;
      u_current_area.base = 0;
      u_current_area.base |= ((uint16_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_current_area.base |= ((uint16_t) (*(inbuffer + offset + 1))) << (8 * 1);
      this->current_area = u_current_area.real;
      offset += sizeof(this->current_area);
      uint32_t completed_areas_lengthT = ((uint32_t) (*(inbuffer + offset)));
      completed_areas_lengthT |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      completed_areas_lengthT |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      completed_areas_lengthT |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      offset += sizeof(this->completed_areas_length);
      if(completed_areas_lengthT > completed_areas_length)
        this->completed_areas = (uint32_t*)realloc(this->completed_areas, completed_areas_lengthT * sizeof(uint32_t));
      completed_areas_length = completed_areas_lengthT;
      for( uint32_t i = 0; i < completed_areas_length; i++){
        union {
          uint32_t real;
          uint32_t base;
        } u_completed_areas[i];
        u_completed_areas[i].base = 0;
        u_completed_areas[i].base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
        u_completed_areas[i].base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
        u_completed_areas[i].base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
        u_completed_areas[i].base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
        this->completed_areas[i] = u_completed_areas[i].real;
        offset += sizeof(this->completed_areas[i]);
      }
      uint32_t attempted_areas_lengthT = ((uint32_t) (*(inbuffer + offset)));
      attempted_areas_lengthT |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      attempted_areas_lengthT |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      attempted_areas_lengthT |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      offset += sizeof(this->attempted_areas_length);
      if(attempted_areas_lengthT > attempted_areas_length)
        this->attempted_areas = (uint32_t*)realloc(this->attempted_areas, attempted_areas_lengthT * sizeof(uint32_t));
      attempted_areas_length = attempted_areas_lengthT;
      for( uint32_t i = 0; i < attempted_areas_length; i++){
        union {
          uint32_t real;
          uint32_t base;
        } u_attempted_areas[i];
        u_attempted_areas[i].base = 0;
        u_attempted_areas[i].base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
        u_attempted_areas[i].base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
        u_attempted_areas[i].base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
        u_attempted_areas[i].base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
        this->attempted_areas[i] = u_attempted_areas[i].real;
        offset += sizeof(this->attempted_areas[i]);
      }
      uint32_t excluded_areas_lengthT = ((uint32_t) (*(inbuffer + offset)));
      excluded_areas_lengthT |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      excluded_areas_lengthT |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      excluded_areas_lengthT |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      offset += sizeof(this->excluded_areas_length);
      if(excluded_areas_lengthT > excluded_areas_length)
        this->excluded_areas = (uint32_t*)realloc(this->excluded_areas, excluded_areas_lengthT * sizeof(uint32_t));
      excluded_areas_length = excluded_areas_lengthT;
      for( uint32_t i = 0; i < excluded_areas_length; i++){
        union {
          uint32_t real;
          uint32_t base;
        } u_excluded_areas[i];
        u_excluded_areas[i].base = 0;
        u_excluded_areas[i].base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
        u_excluded_areas[i].base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
        u_excluded_areas[i].base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
        u_excluded_areas[i].base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
        this->excluded_areas[i] = u_excluded_areas[i].real;
        offset += sizeof(this->excluded_areas[i]);
      }
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/CoverageSession"; };
    virtual const char * getMD5() override { return "fa072d87ca6718991e08a2ff2292e582"; };

  };

}
#endif
