#ifndef _ROS_mower_msgs_DigEvent_h
#define _ROS_mower_msgs_DigEvent_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"
#include "geometry_msgs/Point.h"
#include "std_msgs/Header.h"

namespace mower_msgs
{

  class DigEvent : public ros::Msg
  {
    public:
      typedef std_msgs::Header _header_type;
      _header_type header;
      typedef geometry_msgs::Point _position_type;
      _position_type position;

    DigEvent():
      header(),
      position()
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      offset += this->header.serialize(outbuffer + offset);
      offset += this->position.serialize(outbuffer + offset);
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      offset += this->header.deserialize(inbuffer + offset);
      offset += this->position.deserialize(inbuffer + offset);
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/DigEvent"; };
    virtual const char * getMD5() override { return "8173fc6e99badce3a4906de55228b7b8"; };

  };

}
#endif
