#ifndef _ROS_mower_msgs_DockCalibrationStatus_h
#define _ROS_mower_msgs_DockCalibrationStatus_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"

namespace mower_msgs
{

  class DockCalibrationStatus : public ros::Msg
  {
    public:
      typedef uint8_t _phase_type;
      _phase_type phase;
      typedef bool _success_type;
      _success_type success;
      typedef const char* _message_type;
      _message_type message;
      enum { PHASE_WAIT_RTK = 0 };
      enum { PHASE_REVERSING = 1 };
      enum { PHASE_CHECK_COG = 2 };
      enum { PHASE_REDOCKING = 3 };
      enum { PHASE_VERIFY_CHARGE = 4 };
      enum { PHASE_PERSIST = 5 };
      enum { PHASE_IDLE = 6      # no run has started this session };
      enum { PHASE_DONE = 7      # a run finished (see success/retry_reason) };

    DockCalibrationStatus():
      phase(0),
      success(0),
      message("")
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      *(outbuffer + offset + 0) = (this->phase >> (8 * 0)) & 0xFF;
      offset += sizeof(this->phase);
      union {
        bool real;
        uint8_t base;
      } u_success;
      u_success.real = this->success;
      *(outbuffer + offset + 0) = (u_success.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->success);
      uint32_t length_message = strlen(this->message);
      varToArr(outbuffer + offset, length_message);
      offset += 4;
      memcpy(outbuffer + offset, this->message, length_message);
      offset += length_message;
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      this->phase =  ((uint8_t) (*(inbuffer + offset)));
      offset += sizeof(this->phase);
      union {
        bool real;
        uint8_t base;
      } u_success;
      u_success.base = 0;
      u_success.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->success = u_success.real;
      offset += sizeof(this->success);
      uint32_t length_message;
      arrToVar(length_message, (inbuffer + offset));
      offset += 4;
      for(unsigned int k= offset; k< offset+length_message; ++k){
          inbuffer[k-1]=inbuffer[k];
      }
      inbuffer[offset+length_message-1]=0;
      this->message = (char *)(inbuffer + offset-1);
      offset += length_message;
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/DockCalibrationStatus"; };
    virtual const char * getMD5() override { return "f12dbe5df5c1d2f216567b1a66b20229"; };

  };

}
#endif
