#ifndef _ROS_mower_msgs_FirmwareParams_h
#define _ROS_mower_msgs_FirmwareParams_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"
#include "mower_msgs/FirmwareParam.h"
#include "ros/time.h"

namespace mower_msgs
{

  class FirmwareParams : public ros::Msg
  {
    public:
      typedef ros::Time _stamp_type;
      _stamp_type stamp;
      typedef bool _firmware_incompatible_type;
      _firmware_incompatible_type firmware_incompatible;
      uint32_t params_length;
      typedef mower_msgs::FirmwareParam _params_type;
      _params_type st_params;
      _params_type * params;
      enum { BOOT_UNKNOWN = 255 };
      enum { BOOT_DEFAULTS = 0 };
      enum { BOOT_FLASH = 1 };
      enum { BOOT_FLASH_ERASED = 2 };
      enum { COMMIT_NONE = 0 };
      enum { COMMIT_WRITTEN = 1 };
      enum { COMMIT_UNCHANGED = 2 };
      enum { COMMIT_PENDING = 3 };
      enum { COMMIT_LOG_FULL = 4 };
      enum { COMMIT_ERROR = 5 };

    FirmwareParams():
      stamp(),
      firmware_incompatible(0),
      params_length(0), st_params(), params(nullptr)
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      offset += this->stamp.serialize(outbuffer + offset);
      union {
        bool real;
        uint8_t base;
      } u_firmware_incompatible;
      u_firmware_incompatible.real = this->firmware_incompatible;
      *(outbuffer + offset + 0) = (u_firmware_incompatible.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->firmware_incompatible);
      *(outbuffer + offset + 0) = (this->params_length >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (this->params_length >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (this->params_length >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (this->params_length >> (8 * 3)) & 0xFF;
      offset += sizeof(this->params_length);
      for( uint32_t i = 0; i < params_length; i++){
        offset += this->params[i].serialize(outbuffer + offset);
      }
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      offset += this->stamp.deserialize(inbuffer + offset);
      union {
        bool real;
        uint8_t base;
      } u_firmware_incompatible;
      u_firmware_incompatible.base = 0;
      u_firmware_incompatible.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->firmware_incompatible = u_firmware_incompatible.real;
      offset += sizeof(this->firmware_incompatible);
      uint32_t params_lengthT = ((uint32_t) (*(inbuffer + offset)));
      params_lengthT |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      params_lengthT |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      params_lengthT |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      offset += sizeof(this->params_length);
      if(params_lengthT > params_length)
        this->params = (mower_msgs::FirmwareParam*)realloc(this->params, params_lengthT * sizeof(mower_msgs::FirmwareParam));
      params_length = params_lengthT;
      for( uint32_t i = 0; i < params_length; i++){
        offset += this->params[i].deserialize(inbuffer + offset);
      }
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/FirmwareParams"; };
    virtual const char * getMD5() override { return "de9873be55dffd84ddd5a39622ce1c72"; };

  };

}
#endif
