#ifndef _ROS_mower_msgs_FirmwareParam_h
#define _ROS_mower_msgs_FirmwareParam_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"

namespace mower_msgs
{

  class FirmwareParam : public ros::Msg
  {
    public:
      enum { STATUS_OK = 0 };
      enum { STATUS_CLAMPED = 1 };
      enum { STATUS_UNKNOWN_ID = 2 };
      enum { STATUS_REJECTED = 3 };

    FirmwareParam():

    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/FirmwareParam"; };
    virtual const char * getMD5() override { return "0ea0ad10de6cf05b94461133437c513f"; };

  };

}
#endif
