#ifndef _ROS_mower_msgs_GnssStatus_h
#define _ROS_mower_msgs_GnssStatus_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"
#include "std_msgs/Header.h"

namespace mower_msgs
{

  class GnssStatus : public ros::Msg
  {
    public:
      typedef std_msgs::Header _header_type;
      _header_type header;
      typedef const char* _backend_type;
      _backend_type backend;
      typedef const char* _receiver_vendor_type;
      _receiver_vendor_type receiver_vendor;
      typedef const char* _receiver_model_type;
      _receiver_model_type receiver_model;
      typedef const char* _receiver_firmware_type;
      _receiver_firmware_type receiver_firmware;
      typedef uint8_t _fix_type_type;
      _fix_type_type fix_type;
      typedef bool _fix_valid_type;
      _fix_valid_type fix_valid;
      typedef bool _differential_corrections_type;
      _differential_corrections_type differential_corrections;
      typedef bool _corrections_active_type;
      _corrections_active_type corrections_active;
      typedef bool _dead_reckoning_type;
      _dead_reckoning_type dead_reckoning;
      typedef uint8_t _rtk_mode_type;
      _rtk_mode_type rtk_mode;
      typedef bool _dual_antenna_heading_type;
      _dual_antenna_heading_type dual_antenna_heading;
      typedef bool _interference_detected_type;
      _interference_detected_type interference_detected;
      typedef bool _jamming_detected_type;
      _jamming_detected_type jamming_detected;
      typedef float _quality_percent_type;
      _quality_percent_type quality_percent;
      typedef uint32_t _capability_flags_type;
      _capability_flags_type capability_flags;
      typedef uint32_t _value_flags_type;
      _value_flags_type value_flags;
      typedef float _hdop_type;
      _hdop_type hdop;
      typedef float _vdop_type;
      _vdop_type vdop;
      typedef float _horizontal_accuracy_m_type;
      _horizontal_accuracy_m_type horizontal_accuracy_m;
      typedef float _vertical_accuracy_m_type;
      _vertical_accuracy_m_type vertical_accuracy_m;
      typedef float _heading_deg_type;
      _heading_deg_type heading_deg;
      typedef float _heading_accuracy_deg_type;
      _heading_accuracy_deg_type heading_accuracy_deg;
      typedef uint16_t _satellites_used_type;
      _satellites_used_type satellites_used;
      typedef uint16_t _satellites_visible_type;
      _satellites_visible_type satellites_visible;
      typedef uint16_t _satellites_tracked_type;
      _satellites_tracked_type satellites_tracked;
      typedef float _correction_age_s_type;
      _correction_age_s_type correction_age_s;
      typedef float _mean_cn0_db_hz_type;
      _mean_cn0_db_hz_type mean_cn0_db_hz;
      typedef float _max_cn0_db_hz_type;
      _max_cn0_db_hz_type max_cn0_db_hz;
      typedef bool _dual_antenna_baseline_type;
      _dual_antenna_baseline_type dual_antenna_baseline;
      typedef float _baseline_azimuth_deg_type;
      _baseline_azimuth_deg_type baseline_azimuth_deg;
      typedef float _baseline_pitch_deg_type;
      _baseline_pitch_deg_type baseline_pitch_deg;
      typedef float _baseline_length_m_type;
      _baseline_length_m_type baseline_length_m;
      typedef uint8_t _baseline_solution_status_type;
      _baseline_solution_status_type baseline_solution_status;
      typedef uint8_t _correction_stream_status_type;
      _correction_stream_status_type correction_stream_status;
      typedef bool _msm_summary_seen_type;
      _msm_summary_seen_type msm_summary_seen;
      typedef bool _msm_summary_decoded_type;
      _msm_summary_decoded_type msm_summary_decoded;
      typedef bool _msm_summary_valid_type;
      _msm_summary_valid_type msm_summary_valid;
      typedef uint16_t _msm_summary_message_type_type;
      _msm_summary_message_type_type msm_summary_message_type;
      typedef uint16_t _msm_summary_station_id_type;
      _msm_summary_station_id_type msm_summary_station_id;
      typedef const char* _msm_summary_constellations_seen_type;
      _msm_summary_constellations_seen_type msm_summary_constellations_seen;
      typedef uint16_t _msm_summary_satellite_count_type;
      _msm_summary_satellite_count_type msm_summary_satellite_count;
      typedef uint16_t _msm_summary_signal_count_type;
      _msm_summary_signal_count_type msm_summary_signal_count;
      typedef uint16_t _msm_summary_cell_count_type;
      _msm_summary_cell_count_type msm_summary_cell_count;
      typedef float _msm_summary_age_s_type;
      _msm_summary_age_s_type msm_summary_age_s;
      typedef uint64_t _position_observation_sequence_type;
      _position_observation_sequence_type position_observation_sequence;
      enum { FIX_TYPE_NO_FIX = 0 };
      enum { FIX_TYPE_GPS_FIX = 1 };
      enum { FIX_TYPE_RTK_FLOAT = 2 };
      enum { FIX_TYPE_RTK_FIXED = 3 };
      enum { FIX_TYPE_DEAD_RECKONING = 4 };
      enum { RTK_MODE_UNKNOWN = 0 };
      enum { RTK_MODE_NONE = 1 };
      enum { RTK_MODE_FLOAT = 2 };
      enum { RTK_MODE_FIXED = 3 };
      enum { BASELINE_STATUS_UNKNOWN = 0 };
      enum { BASELINE_STATUS_COMPUTED = 1 };
      enum { BASELINE_STATUS_NOT_SOLVED = 2 };
      enum { BASELINE_STATUS_INSUFFICIENT_OBSERVATIONS = 3 };
      enum { BASELINE_STATUS_NO_CONVERGENCE = 4 };
      enum { BASELINE_STATUS_OUT_OF_TOLERANCE = 5 };
      enum { BASELINE_STATUS_COVARIANCE_TRACE_EXCEEDED = 6 };
      enum { BASELINE_STATUS_NOT_CONFIGURED = 7 };
      enum { CORRECTION_STREAM_STATUS_UNKNOWN = 0 };
      enum { CORRECTION_STREAM_STATUS_IDLE = 1 };
      enum { CORRECTION_STREAM_STATUS_WAITING = 2 };
      enum { CORRECTION_STREAM_STATUS_ACTIVE = 3 };
      enum { CORRECTION_STREAM_STATUS_UNAVAILABLE = 4 };
      enum { CORRECTION_STREAM_STATUS_ERROR = 5 };
      enum { CAP_RTK_MODE = 1 };
      enum { CAP_HDOP = 2 };
      enum { CAP_VDOP = 4 };
      enum { CAP_HORIZONTAL_ACCURACY = 8 };
      enum { CAP_VERTICAL_ACCURACY = 16 };
      enum { CAP_HEADING = 32 };
      enum { CAP_HEADING_ACCURACY = 64 };
      enum { CAP_SATELLITES_USED = 128 };
      enum { CAP_SATELLITES_VISIBLE = 256 };
      enum { CAP_SATELLITES_TRACKED = 512 };
      enum { CAP_DIFFERENTIAL_CORRECTIONS = 1024 };
      enum { CAP_CORRECTIONS_ACTIVE = 2048 };
      enum { CAP_CORRECTION_AGE = 4096 };
      enum { CAP_MEAN_CN0 = 8192 };
      enum { CAP_MAX_CN0 = 16384 };
      enum { CAP_DUAL_ANTENNA_STATUS = 32768 };
      enum { CAP_INTERFERENCE_STATUS = 65536 };
      enum { CAP_JAMMING_STATUS = 131072 };
      enum { CAP_DUAL_ANTENNA_BASELINE = 262144 };
      enum { CAP_BASELINE_AZIMUTH = 524288 };
      enum { CAP_BASELINE_PITCH = 1048576 };
      enum { CAP_BASELINE_LENGTH = 2097152 };
      enum { CAP_BASELINE_SOLUTION_STATUS = 4194304 };
      enum { CAP_CORRECTION_STREAM = 8388608 };
      enum { CAP_MSM_SUMMARY = 16777216 };

    GnssStatus():
      header(),
      backend(""),
      receiver_vendor(""),
      receiver_model(""),
      receiver_firmware(""),
      fix_type(0),
      fix_valid(0),
      differential_corrections(0),
      corrections_active(0),
      dead_reckoning(0),
      rtk_mode(0),
      dual_antenna_heading(0),
      interference_detected(0),
      jamming_detected(0),
      quality_percent(0),
      capability_flags(0),
      value_flags(0),
      hdop(0),
      vdop(0),
      horizontal_accuracy_m(0),
      vertical_accuracy_m(0),
      heading_deg(0),
      heading_accuracy_deg(0),
      satellites_used(0),
      satellites_visible(0),
      satellites_tracked(0),
      correction_age_s(0),
      mean_cn0_db_hz(0),
      max_cn0_db_hz(0),
      dual_antenna_baseline(0),
      baseline_azimuth_deg(0),
      baseline_pitch_deg(0),
      baseline_length_m(0),
      baseline_solution_status(0),
      correction_stream_status(0),
      msm_summary_seen(0),
      msm_summary_decoded(0),
      msm_summary_valid(0),
      msm_summary_message_type(0),
      msm_summary_station_id(0),
      msm_summary_constellations_seen(""),
      msm_summary_satellite_count(0),
      msm_summary_signal_count(0),
      msm_summary_cell_count(0),
      msm_summary_age_s(0),
      position_observation_sequence(0)
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      offset += this->header.serialize(outbuffer + offset);
      uint32_t length_backend = strlen(this->backend);
      varToArr(outbuffer + offset, length_backend);
      offset += 4;
      memcpy(outbuffer + offset, this->backend, length_backend);
      offset += length_backend;
      uint32_t length_receiver_vendor = strlen(this->receiver_vendor);
      varToArr(outbuffer + offset, length_receiver_vendor);
      offset += 4;
      memcpy(outbuffer + offset, this->receiver_vendor, length_receiver_vendor);
      offset += length_receiver_vendor;
      uint32_t length_receiver_model = strlen(this->receiver_model);
      varToArr(outbuffer + offset, length_receiver_model);
      offset += 4;
      memcpy(outbuffer + offset, this->receiver_model, length_receiver_model);
      offset += length_receiver_model;
      uint32_t length_receiver_firmware = strlen(this->receiver_firmware);
      varToArr(outbuffer + offset, length_receiver_firmware);
      offset += 4;
      memcpy(outbuffer + offset, this->receiver_firmware, length_receiver_firmware);
      offset += length_receiver_firmware;
      *(outbuffer + offset + 0) = (this->fix_type >> (8 * 0)) & 0xFF;
      offset += sizeof(this->fix_type);
      union {
        bool real;
        uint8_t base;
      } u_fix_valid;
      u_fix_valid.real = this->fix_valid;
      *(outbuffer + offset + 0) = (u_fix_valid.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->fix_valid);
      union {
        bool real;
        uint8_t base;
      } u_differential_corrections;
      u_differential_corrections.real = this->differential_corrections;
      *(outbuffer + offset + 0) = (u_differential_corrections.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->differential_corrections);
      union {
        bool real;
        uint8_t base;
      } u_corrections_active;
      u_corrections_active.real = this->corrections_active;
      *(outbuffer + offset + 0) = (u_corrections_active.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->corrections_active);
      union {
        bool real;
        uint8_t base;
      } u_dead_reckoning;
      u_dead_reckoning.real = this->dead_reckoning;
      *(outbuffer + offset + 0) = (u_dead_reckoning.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->dead_reckoning);
      *(outbuffer + offset + 0) = (this->rtk_mode >> (8 * 0)) & 0xFF;
      offset += sizeof(this->rtk_mode);
      union {
        bool real;
        uint8_t base;
      } u_dual_antenna_heading;
      u_dual_antenna_heading.real = this->dual_antenna_heading;
      *(outbuffer + offset + 0) = (u_dual_antenna_heading.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->dual_antenna_heading);
      union {
        bool real;
        uint8_t base;
      } u_interference_detected;
      u_interference_detected.real = this->interference_detected;
      *(outbuffer + offset + 0) = (u_interference_detected.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->interference_detected);
      union {
        bool real;
        uint8_t base;
      } u_jamming_detected;
      u_jamming_detected.real = this->jamming_detected;
      *(outbuffer + offset + 0) = (u_jamming_detected.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->jamming_detected);
      union {
        float real;
        uint32_t base;
      } u_quality_percent;
      u_quality_percent.real = this->quality_percent;
      *(outbuffer + offset + 0) = (u_quality_percent.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_quality_percent.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_quality_percent.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_quality_percent.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->quality_percent);
      union {
        uint32_t real;
        uint32_t base;
      } u_capability_flags;
      u_capability_flags.real = this->capability_flags;
      *(outbuffer + offset + 0) = (u_capability_flags.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_capability_flags.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_capability_flags.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_capability_flags.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->capability_flags);
      union {
        uint32_t real;
        uint32_t base;
      } u_value_flags;
      u_value_flags.real = this->value_flags;
      *(outbuffer + offset + 0) = (u_value_flags.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_value_flags.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_value_flags.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_value_flags.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->value_flags);
      union {
        float real;
        uint32_t base;
      } u_hdop;
      u_hdop.real = this->hdop;
      *(outbuffer + offset + 0) = (u_hdop.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_hdop.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_hdop.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_hdop.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->hdop);
      union {
        float real;
        uint32_t base;
      } u_vdop;
      u_vdop.real = this->vdop;
      *(outbuffer + offset + 0) = (u_vdop.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_vdop.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_vdop.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_vdop.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->vdop);
      union {
        float real;
        uint32_t base;
      } u_horizontal_accuracy_m;
      u_horizontal_accuracy_m.real = this->horizontal_accuracy_m;
      *(outbuffer + offset + 0) = (u_horizontal_accuracy_m.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_horizontal_accuracy_m.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_horizontal_accuracy_m.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_horizontal_accuracy_m.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->horizontal_accuracy_m);
      union {
        float real;
        uint32_t base;
      } u_vertical_accuracy_m;
      u_vertical_accuracy_m.real = this->vertical_accuracy_m;
      *(outbuffer + offset + 0) = (u_vertical_accuracy_m.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_vertical_accuracy_m.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_vertical_accuracy_m.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_vertical_accuracy_m.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->vertical_accuracy_m);
      union {
        float real;
        uint32_t base;
      } u_heading_deg;
      u_heading_deg.real = this->heading_deg;
      *(outbuffer + offset + 0) = (u_heading_deg.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_heading_deg.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_heading_deg.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_heading_deg.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->heading_deg);
      union {
        float real;
        uint32_t base;
      } u_heading_accuracy_deg;
      u_heading_accuracy_deg.real = this->heading_accuracy_deg;
      *(outbuffer + offset + 0) = (u_heading_accuracy_deg.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_heading_accuracy_deg.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_heading_accuracy_deg.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_heading_accuracy_deg.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->heading_accuracy_deg);
      union {
        uint16_t real;
        uint16_t base;
      } u_satellites_used;
      u_satellites_used.real = this->satellites_used;
      *(outbuffer + offset + 0) = (u_satellites_used.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_satellites_used.base >> (8 * 1)) & 0xFF;
      offset += sizeof(this->satellites_used);
      union {
        uint16_t real;
        uint16_t base;
      } u_satellites_visible;
      u_satellites_visible.real = this->satellites_visible;
      *(outbuffer + offset + 0) = (u_satellites_visible.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_satellites_visible.base >> (8 * 1)) & 0xFF;
      offset += sizeof(this->satellites_visible);
      union {
        uint16_t real;
        uint16_t base;
      } u_satellites_tracked;
      u_satellites_tracked.real = this->satellites_tracked;
      *(outbuffer + offset + 0) = (u_satellites_tracked.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_satellites_tracked.base >> (8 * 1)) & 0xFF;
      offset += sizeof(this->satellites_tracked);
      union {
        float real;
        uint32_t base;
      } u_correction_age_s;
      u_correction_age_s.real = this->correction_age_s;
      *(outbuffer + offset + 0) = (u_correction_age_s.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_correction_age_s.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_correction_age_s.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_correction_age_s.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->correction_age_s);
      union {
        float real;
        uint32_t base;
      } u_mean_cn0_db_hz;
      u_mean_cn0_db_hz.real = this->mean_cn0_db_hz;
      *(outbuffer + offset + 0) = (u_mean_cn0_db_hz.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_mean_cn0_db_hz.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_mean_cn0_db_hz.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_mean_cn0_db_hz.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->mean_cn0_db_hz);
      union {
        float real;
        uint32_t base;
      } u_max_cn0_db_hz;
      u_max_cn0_db_hz.real = this->max_cn0_db_hz;
      *(outbuffer + offset + 0) = (u_max_cn0_db_hz.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_max_cn0_db_hz.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_max_cn0_db_hz.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_max_cn0_db_hz.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->max_cn0_db_hz);
      union {
        bool real;
        uint8_t base;
      } u_dual_antenna_baseline;
      u_dual_antenna_baseline.real = this->dual_antenna_baseline;
      *(outbuffer + offset + 0) = (u_dual_antenna_baseline.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->dual_antenna_baseline);
      union {
        float real;
        uint32_t base;
      } u_baseline_azimuth_deg;
      u_baseline_azimuth_deg.real = this->baseline_azimuth_deg;
      *(outbuffer + offset + 0) = (u_baseline_azimuth_deg.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_baseline_azimuth_deg.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_baseline_azimuth_deg.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_baseline_azimuth_deg.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->baseline_azimuth_deg);
      union {
        float real;
        uint32_t base;
      } u_baseline_pitch_deg;
      u_baseline_pitch_deg.real = this->baseline_pitch_deg;
      *(outbuffer + offset + 0) = (u_baseline_pitch_deg.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_baseline_pitch_deg.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_baseline_pitch_deg.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_baseline_pitch_deg.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->baseline_pitch_deg);
      union {
        float real;
        uint32_t base;
      } u_baseline_length_m;
      u_baseline_length_m.real = this->baseline_length_m;
      *(outbuffer + offset + 0) = (u_baseline_length_m.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_baseline_length_m.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_baseline_length_m.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_baseline_length_m.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->baseline_length_m);
      *(outbuffer + offset + 0) = (this->baseline_solution_status >> (8 * 0)) & 0xFF;
      offset += sizeof(this->baseline_solution_status);
      *(outbuffer + offset + 0) = (this->correction_stream_status >> (8 * 0)) & 0xFF;
      offset += sizeof(this->correction_stream_status);
      union {
        bool real;
        uint8_t base;
      } u_msm_summary_seen;
      u_msm_summary_seen.real = this->msm_summary_seen;
      *(outbuffer + offset + 0) = (u_msm_summary_seen.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->msm_summary_seen);
      union {
        bool real;
        uint8_t base;
      } u_msm_summary_decoded;
      u_msm_summary_decoded.real = this->msm_summary_decoded;
      *(outbuffer + offset + 0) = (u_msm_summary_decoded.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->msm_summary_decoded);
      union {
        bool real;
        uint8_t base;
      } u_msm_summary_valid;
      u_msm_summary_valid.real = this->msm_summary_valid;
      *(outbuffer + offset + 0) = (u_msm_summary_valid.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->msm_summary_valid);
      union {
        uint16_t real;
        uint16_t base;
      } u_msm_summary_message_type;
      u_msm_summary_message_type.real = this->msm_summary_message_type;
      *(outbuffer + offset + 0) = (u_msm_summary_message_type.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_msm_summary_message_type.base >> (8 * 1)) & 0xFF;
      offset += sizeof(this->msm_summary_message_type);
      union {
        uint16_t real;
        uint16_t base;
      } u_msm_summary_station_id;
      u_msm_summary_station_id.real = this->msm_summary_station_id;
      *(outbuffer + offset + 0) = (u_msm_summary_station_id.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_msm_summary_station_id.base >> (8 * 1)) & 0xFF;
      offset += sizeof(this->msm_summary_station_id);
      uint32_t length_msm_summary_constellations_seen = strlen(this->msm_summary_constellations_seen);
      varToArr(outbuffer + offset, length_msm_summary_constellations_seen);
      offset += 4;
      memcpy(outbuffer + offset, this->msm_summary_constellations_seen, length_msm_summary_constellations_seen);
      offset += length_msm_summary_constellations_seen;
      union {
        uint16_t real;
        uint16_t base;
      } u_msm_summary_satellite_count;
      u_msm_summary_satellite_count.real = this->msm_summary_satellite_count;
      *(outbuffer + offset + 0) = (u_msm_summary_satellite_count.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_msm_summary_satellite_count.base >> (8 * 1)) & 0xFF;
      offset += sizeof(this->msm_summary_satellite_count);
      union {
        uint16_t real;
        uint16_t base;
      } u_msm_summary_signal_count;
      u_msm_summary_signal_count.real = this->msm_summary_signal_count;
      *(outbuffer + offset + 0) = (u_msm_summary_signal_count.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_msm_summary_signal_count.base >> (8 * 1)) & 0xFF;
      offset += sizeof(this->msm_summary_signal_count);
      union {
        uint16_t real;
        uint16_t base;
      } u_msm_summary_cell_count;
      u_msm_summary_cell_count.real = this->msm_summary_cell_count;
      *(outbuffer + offset + 0) = (u_msm_summary_cell_count.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_msm_summary_cell_count.base >> (8 * 1)) & 0xFF;
      offset += sizeof(this->msm_summary_cell_count);
      union {
        float real;
        uint32_t base;
      } u_msm_summary_age_s;
      u_msm_summary_age_s.real = this->msm_summary_age_s;
      *(outbuffer + offset + 0) = (u_msm_summary_age_s.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_msm_summary_age_s.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_msm_summary_age_s.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_msm_summary_age_s.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->msm_summary_age_s);
      union {
        uint64_t real;
        uint64_t base;
      } u_position_observation_sequence;
      u_position_observation_sequence.real = this->position_observation_sequence;
      *(outbuffer + offset + 0) = (u_position_observation_sequence.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_position_observation_sequence.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_position_observation_sequence.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_position_observation_sequence.base >> (8 * 3)) & 0xFF;
      *(outbuffer + offset + 4) = (u_position_observation_sequence.base >> (8 * 4)) & 0xFF;
      *(outbuffer + offset + 5) = (u_position_observation_sequence.base >> (8 * 5)) & 0xFF;
      *(outbuffer + offset + 6) = (u_position_observation_sequence.base >> (8 * 6)) & 0xFF;
      *(outbuffer + offset + 7) = (u_position_observation_sequence.base >> (8 * 7)) & 0xFF;
      offset += sizeof(this->position_observation_sequence);
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      offset += this->header.deserialize(inbuffer + offset);
      uint32_t length_backend;
      arrToVar(length_backend, (inbuffer + offset));
      offset += 4;
      for(unsigned int k= offset; k< offset+length_backend; ++k){
          inbuffer[k-1]=inbuffer[k];
      }
      inbuffer[offset+length_backend-1]=0;
      this->backend = (char *)(inbuffer + offset-1);
      offset += length_backend;
      uint32_t length_receiver_vendor;
      arrToVar(length_receiver_vendor, (inbuffer + offset));
      offset += 4;
      for(unsigned int k= offset; k< offset+length_receiver_vendor; ++k){
          inbuffer[k-1]=inbuffer[k];
      }
      inbuffer[offset+length_receiver_vendor-1]=0;
      this->receiver_vendor = (char *)(inbuffer + offset-1);
      offset += length_receiver_vendor;
      uint32_t length_receiver_model;
      arrToVar(length_receiver_model, (inbuffer + offset));
      offset += 4;
      for(unsigned int k= offset; k< offset+length_receiver_model; ++k){
          inbuffer[k-1]=inbuffer[k];
      }
      inbuffer[offset+length_receiver_model-1]=0;
      this->receiver_model = (char *)(inbuffer + offset-1);
      offset += length_receiver_model;
      uint32_t length_receiver_firmware;
      arrToVar(length_receiver_firmware, (inbuffer + offset));
      offset += 4;
      for(unsigned int k= offset; k< offset+length_receiver_firmware; ++k){
          inbuffer[k-1]=inbuffer[k];
      }
      inbuffer[offset+length_receiver_firmware-1]=0;
      this->receiver_firmware = (char *)(inbuffer + offset-1);
      offset += length_receiver_firmware;
      this->fix_type =  ((uint8_t) (*(inbuffer + offset)));
      offset += sizeof(this->fix_type);
      union {
        bool real;
        uint8_t base;
      } u_fix_valid;
      u_fix_valid.base = 0;
      u_fix_valid.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->fix_valid = u_fix_valid.real;
      offset += sizeof(this->fix_valid);
      union {
        bool real;
        uint8_t base;
      } u_differential_corrections;
      u_differential_corrections.base = 0;
      u_differential_corrections.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->differential_corrections = u_differential_corrections.real;
      offset += sizeof(this->differential_corrections);
      union {
        bool real;
        uint8_t base;
      } u_corrections_active;
      u_corrections_active.base = 0;
      u_corrections_active.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->corrections_active = u_corrections_active.real;
      offset += sizeof(this->corrections_active);
      union {
        bool real;
        uint8_t base;
      } u_dead_reckoning;
      u_dead_reckoning.base = 0;
      u_dead_reckoning.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->dead_reckoning = u_dead_reckoning.real;
      offset += sizeof(this->dead_reckoning);
      this->rtk_mode =  ((uint8_t) (*(inbuffer + offset)));
      offset += sizeof(this->rtk_mode);
      union {
        bool real;
        uint8_t base;
      } u_dual_antenna_heading;
      u_dual_antenna_heading.base = 0;
      u_dual_antenna_heading.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->dual_antenna_heading = u_dual_antenna_heading.real;
      offset += sizeof(this->dual_antenna_heading);
      union {
        bool real;
        uint8_t base;
      } u_interference_detected;
      u_interference_detected.base = 0;
      u_interference_detected.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->interference_detected = u_interference_detected.real;
      offset += sizeof(this->interference_detected);
      union {
        bool real;
        uint8_t base;
      } u_jamming_detected;
      u_jamming_detected.base = 0;
      u_jamming_detected.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->jamming_detected = u_jamming_detected.real;
      offset += sizeof(this->jamming_detected);
      union {
        float real;
        uint32_t base;
      } u_quality_percent;
      u_quality_percent.base = 0;
      u_quality_percent.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_quality_percent.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_quality_percent.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_quality_percent.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->quality_percent = u_quality_percent.real;
      offset += sizeof(this->quality_percent);
      union {
        uint32_t real;
        uint32_t base;
      } u_capability_flags;
      u_capability_flags.base = 0;
      u_capability_flags.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_capability_flags.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_capability_flags.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_capability_flags.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->capability_flags = u_capability_flags.real;
      offset += sizeof(this->capability_flags);
      union {
        uint32_t real;
        uint32_t base;
      } u_value_flags;
      u_value_flags.base = 0;
      u_value_flags.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_value_flags.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_value_flags.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_value_flags.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->value_flags = u_value_flags.real;
      offset += sizeof(this->value_flags);
      union {
        float real;
        uint32_t base;
      } u_hdop;
      u_hdop.base = 0;
      u_hdop.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_hdop.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_hdop.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_hdop.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->hdop = u_hdop.real;
      offset += sizeof(this->hdop);
      union {
        float real;
        uint32_t base;
      } u_vdop;
      u_vdop.base = 0;
      u_vdop.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_vdop.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_vdop.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_vdop.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->vdop = u_vdop.real;
      offset += sizeof(this->vdop);
      union {
        float real;
        uint32_t base;
      } u_horizontal_accuracy_m;
      u_horizontal_accuracy_m.base = 0;
      u_horizontal_accuracy_m.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_horizontal_accuracy_m.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_horizontal_accuracy_m.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_horizontal_accuracy_m.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->horizontal_accuracy_m = u_horizontal_accuracy_m.real;
      offset += sizeof(this->horizontal_accuracy_m);
      union {
        float real;
        uint32_t base;
      } u_vertical_accuracy_m;
      u_vertical_accuracy_m.base = 0;
      u_vertical_accuracy_m.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_vertical_accuracy_m.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_vertical_accuracy_m.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_vertical_accuracy_m.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->vertical_accuracy_m = u_vertical_accuracy_m.real;
      offset += sizeof(this->vertical_accuracy_m);
      union {
        float real;
        uint32_t base;
      } u_heading_deg;
      u_heading_deg.base = 0;
      u_heading_deg.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_heading_deg.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_heading_deg.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_heading_deg.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->heading_deg = u_heading_deg.real;
      offset += sizeof(this->heading_deg);
      union {
        float real;
        uint32_t base;
      } u_heading_accuracy_deg;
      u_heading_accuracy_deg.base = 0;
      u_heading_accuracy_deg.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_heading_accuracy_deg.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_heading_accuracy_deg.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_heading_accuracy_deg.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->heading_accuracy_deg = u_heading_accuracy_deg.real;
      offset += sizeof(this->heading_accuracy_deg);
      union {
        uint16_t real;
        uint16_t base;
      } u_satellites_used;
      u_satellites_used.base = 0;
      u_satellites_used.base |= ((uint16_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_satellites_used.base |= ((uint16_t) (*(inbuffer + offset + 1))) << (8 * 1);
      this->satellites_used = u_satellites_used.real;
      offset += sizeof(this->satellites_used);
      union {
        uint16_t real;
        uint16_t base;
      } u_satellites_visible;
      u_satellites_visible.base = 0;
      u_satellites_visible.base |= ((uint16_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_satellites_visible.base |= ((uint16_t) (*(inbuffer + offset + 1))) << (8 * 1);
      this->satellites_visible = u_satellites_visible.real;
      offset += sizeof(this->satellites_visible);
      union {
        uint16_t real;
        uint16_t base;
      } u_satellites_tracked;
      u_satellites_tracked.base = 0;
      u_satellites_tracked.base |= ((uint16_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_satellites_tracked.base |= ((uint16_t) (*(inbuffer + offset + 1))) << (8 * 1);
      this->satellites_tracked = u_satellites_tracked.real;
      offset += sizeof(this->satellites_tracked);
      union {
        float real;
        uint32_t base;
      } u_correction_age_s;
      u_correction_age_s.base = 0;
      u_correction_age_s.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_correction_age_s.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_correction_age_s.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_correction_age_s.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->correction_age_s = u_correction_age_s.real;
      offset += sizeof(this->correction_age_s);
      union {
        float real;
        uint32_t base;
      } u_mean_cn0_db_hz;
      u_mean_cn0_db_hz.base = 0;
      u_mean_cn0_db_hz.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_mean_cn0_db_hz.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_mean_cn0_db_hz.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_mean_cn0_db_hz.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->mean_cn0_db_hz = u_mean_cn0_db_hz.real;
      offset += sizeof(this->mean_cn0_db_hz);
      union {
        float real;
        uint32_t base;
      } u_max_cn0_db_hz;
      u_max_cn0_db_hz.base = 0;
      u_max_cn0_db_hz.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_max_cn0_db_hz.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_max_cn0_db_hz.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_max_cn0_db_hz.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->max_cn0_db_hz = u_max_cn0_db_hz.real;
      offset += sizeof(this->max_cn0_db_hz);
      union {
        bool real;
        uint8_t base;
      } u_dual_antenna_baseline;
      u_dual_antenna_baseline.base = 0;
      u_dual_antenna_baseline.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->dual_antenna_baseline = u_dual_antenna_baseline.real;
      offset += sizeof(this->dual_antenna_baseline);
      union {
        float real;
        uint32_t base;
      } u_baseline_azimuth_deg;
      u_baseline_azimuth_deg.base = 0;
      u_baseline_azimuth_deg.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_baseline_azimuth_deg.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_baseline_azimuth_deg.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_baseline_azimuth_deg.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->baseline_azimuth_deg = u_baseline_azimuth_deg.real;
      offset += sizeof(this->baseline_azimuth_deg);
      union {
        float real;
        uint32_t base;
      } u_baseline_pitch_deg;
      u_baseline_pitch_deg.base = 0;
      u_baseline_pitch_deg.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_baseline_pitch_deg.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_baseline_pitch_deg.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_baseline_pitch_deg.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->baseline_pitch_deg = u_baseline_pitch_deg.real;
      offset += sizeof(this->baseline_pitch_deg);
      union {
        float real;
        uint32_t base;
      } u_baseline_length_m;
      u_baseline_length_m.base = 0;
      u_baseline_length_m.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_baseline_length_m.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_baseline_length_m.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_baseline_length_m.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->baseline_length_m = u_baseline_length_m.real;
      offset += sizeof(this->baseline_length_m);
      this->baseline_solution_status =  ((uint8_t) (*(inbuffer + offset)));
      offset += sizeof(this->baseline_solution_status);
      this->correction_stream_status =  ((uint8_t) (*(inbuffer + offset)));
      offset += sizeof(this->correction_stream_status);
      union {
        bool real;
        uint8_t base;
      } u_msm_summary_seen;
      u_msm_summary_seen.base = 0;
      u_msm_summary_seen.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->msm_summary_seen = u_msm_summary_seen.real;
      offset += sizeof(this->msm_summary_seen);
      union {
        bool real;
        uint8_t base;
      } u_msm_summary_decoded;
      u_msm_summary_decoded.base = 0;
      u_msm_summary_decoded.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->msm_summary_decoded = u_msm_summary_decoded.real;
      offset += sizeof(this->msm_summary_decoded);
      union {
        bool real;
        uint8_t base;
      } u_msm_summary_valid;
      u_msm_summary_valid.base = 0;
      u_msm_summary_valid.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->msm_summary_valid = u_msm_summary_valid.real;
      offset += sizeof(this->msm_summary_valid);
      union {
        uint16_t real;
        uint16_t base;
      } u_msm_summary_message_type;
      u_msm_summary_message_type.base = 0;
      u_msm_summary_message_type.base |= ((uint16_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_msm_summary_message_type.base |= ((uint16_t) (*(inbuffer + offset + 1))) << (8 * 1);
      this->msm_summary_message_type = u_msm_summary_message_type.real;
      offset += sizeof(this->msm_summary_message_type);
      union {
        uint16_t real;
        uint16_t base;
      } u_msm_summary_station_id;
      u_msm_summary_station_id.base = 0;
      u_msm_summary_station_id.base |= ((uint16_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_msm_summary_station_id.base |= ((uint16_t) (*(inbuffer + offset + 1))) << (8 * 1);
      this->msm_summary_station_id = u_msm_summary_station_id.real;
      offset += sizeof(this->msm_summary_station_id);
      uint32_t length_msm_summary_constellations_seen;
      arrToVar(length_msm_summary_constellations_seen, (inbuffer + offset));
      offset += 4;
      for(unsigned int k= offset; k< offset+length_msm_summary_constellations_seen; ++k){
          inbuffer[k-1]=inbuffer[k];
      }
      inbuffer[offset+length_msm_summary_constellations_seen-1]=0;
      this->msm_summary_constellations_seen = (char *)(inbuffer + offset-1);
      offset += length_msm_summary_constellations_seen;
      union {
        uint16_t real;
        uint16_t base;
      } u_msm_summary_satellite_count;
      u_msm_summary_satellite_count.base = 0;
      u_msm_summary_satellite_count.base |= ((uint16_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_msm_summary_satellite_count.base |= ((uint16_t) (*(inbuffer + offset + 1))) << (8 * 1);
      this->msm_summary_satellite_count = u_msm_summary_satellite_count.real;
      offset += sizeof(this->msm_summary_satellite_count);
      union {
        uint16_t real;
        uint16_t base;
      } u_msm_summary_signal_count;
      u_msm_summary_signal_count.base = 0;
      u_msm_summary_signal_count.base |= ((uint16_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_msm_summary_signal_count.base |= ((uint16_t) (*(inbuffer + offset + 1))) << (8 * 1);
      this->msm_summary_signal_count = u_msm_summary_signal_count.real;
      offset += sizeof(this->msm_summary_signal_count);
      union {
        uint16_t real;
        uint16_t base;
      } u_msm_summary_cell_count;
      u_msm_summary_cell_count.base = 0;
      u_msm_summary_cell_count.base |= ((uint16_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_msm_summary_cell_count.base |= ((uint16_t) (*(inbuffer + offset + 1))) << (8 * 1);
      this->msm_summary_cell_count = u_msm_summary_cell_count.real;
      offset += sizeof(this->msm_summary_cell_count);
      union {
        float real;
        uint32_t base;
      } u_msm_summary_age_s;
      u_msm_summary_age_s.base = 0;
      u_msm_summary_age_s.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_msm_summary_age_s.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_msm_summary_age_s.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_msm_summary_age_s.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->msm_summary_age_s = u_msm_summary_age_s.real;
      offset += sizeof(this->msm_summary_age_s);
      union {
        uint64_t real;
        uint64_t base;
      } u_position_observation_sequence;
      u_position_observation_sequence.base = 0;
      u_position_observation_sequence.base |= ((uint64_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_position_observation_sequence.base |= ((uint64_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_position_observation_sequence.base |= ((uint64_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_position_observation_sequence.base |= ((uint64_t) (*(inbuffer + offset + 3))) << (8 * 3);
      u_position_observation_sequence.base |= ((uint64_t) (*(inbuffer + offset + 4))) << (8 * 4);
      u_position_observation_sequence.base |= ((uint64_t) (*(inbuffer + offset + 5))) << (8 * 5);
      u_position_observation_sequence.base |= ((uint64_t) (*(inbuffer + offset + 6))) << (8 * 6);
      u_position_observation_sequence.base |= ((uint64_t) (*(inbuffer + offset + 7))) << (8 * 7);
      this->position_observation_sequence = u_position_observation_sequence.real;
      offset += sizeof(this->position_observation_sequence);
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/GnssStatus"; };
    virtual const char * getMD5() override { return "2abb8ee551e47aac5db970d0e1a1740b"; };

  };

}
#endif
