#ifndef _ROS_mower_msgs_LidarIgnoreCorridor_h
#define _ROS_mower_msgs_LidarIgnoreCorridor_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"
#include "geometry_msgs/Polygon.h"

namespace mower_msgs
{

  class LidarIgnoreCorridor : public ros::Msg
  {
    public:
      typedef const char* _name_type;
      _name_type name;
      typedef geometry_msgs::Polygon _polyline_type;
      _polyline_type polyline;
      typedef double _width_m_type;
      _width_m_type width_m;
      typedef uint32_t _id_type;
      _id_type id;

    LidarIgnoreCorridor():
      name(""),
      polyline(),
      width_m(0),
      id(0)
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      uint32_t length_name = strlen(this->name);
      varToArr(outbuffer + offset, length_name);
      offset += 4;
      memcpy(outbuffer + offset, this->name, length_name);
      offset += length_name;
      offset += this->polyline.serialize(outbuffer + offset);
      union {
        double real;
        uint64_t base;
      } u_width_m;
      u_width_m.real = this->width_m;
      *(outbuffer + offset + 0) = (u_width_m.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_width_m.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_width_m.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_width_m.base >> (8 * 3)) & 0xFF;
      *(outbuffer + offset + 4) = (u_width_m.base >> (8 * 4)) & 0xFF;
      *(outbuffer + offset + 5) = (u_width_m.base >> (8 * 5)) & 0xFF;
      *(outbuffer + offset + 6) = (u_width_m.base >> (8 * 6)) & 0xFF;
      *(outbuffer + offset + 7) = (u_width_m.base >> (8 * 7)) & 0xFF;
      offset += sizeof(this->width_m);
      union {
        uint32_t real;
        uint32_t base;
      } u_id;
      u_id.real = this->id;
      *(outbuffer + offset + 0) = (u_id.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_id.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_id.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_id.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->id);
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      uint32_t length_name;
      arrToVar(length_name, (inbuffer + offset));
      offset += 4;
      for(unsigned int k= offset; k< offset+length_name; ++k){
          inbuffer[k-1]=inbuffer[k];
      }
      inbuffer[offset+length_name-1]=0;
      this->name = (char *)(inbuffer + offset-1);
      offset += length_name;
      offset += this->polyline.deserialize(inbuffer + offset);
      union {
        double real;
        uint64_t base;
      } u_width_m;
      u_width_m.base = 0;
      u_width_m.base |= ((uint64_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_width_m.base |= ((uint64_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_width_m.base |= ((uint64_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_width_m.base |= ((uint64_t) (*(inbuffer + offset + 3))) << (8 * 3);
      u_width_m.base |= ((uint64_t) (*(inbuffer + offset + 4))) << (8 * 4);
      u_width_m.base |= ((uint64_t) (*(inbuffer + offset + 5))) << (8 * 5);
      u_width_m.base |= ((uint64_t) (*(inbuffer + offset + 6))) << (8 * 6);
      u_width_m.base |= ((uint64_t) (*(inbuffer + offset + 7))) << (8 * 7);
      this->width_m = u_width_m.real;
      offset += sizeof(this->width_m);
      union {
        uint32_t real;
        uint32_t base;
      } u_id;
      u_id.base = 0;
      u_id.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_id.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_id.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_id.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->id = u_id.real;
      offset += sizeof(this->id);
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/LidarIgnoreCorridor"; };
    virtual const char * getMD5() override { return "9c80bda0566e03e16e338fb21cff7214"; };

  };

}
#endif
