#ifndef _ROS_mower_msgs_MapArea_h
#define _ROS_mower_msgs_MapArea_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"
#include "geometry_msgs/Polygon.h"
#include "mower_msgs/MapObstacleInfo.h"

namespace mower_msgs
{

  class MapArea : public ros::Msg
  {
    public:
      typedef const char* _name_type;
      _name_type name;
      typedef geometry_msgs::Polygon _area_type;
      _area_type area;
      uint32_t obstacles_length;
      typedef geometry_msgs::Polygon _obstacles_type;
      _obstacles_type st_obstacles;
      _obstacles_type * obstacles;
      typedef bool _is_navigation_area_type;
      _is_navigation_area_type is_navigation_area;
      uint32_t obstacle_info_length;
      typedef mower_msgs::MapObstacleInfo _obstacle_info_type;
      _obstacle_info_type st_obstacle_info;
      _obstacle_info_type * obstacle_info;
      uint32_t proposed_obstacles_length;
      typedef geometry_msgs::Polygon _proposed_obstacles_type;
      _proposed_obstacles_type st_proposed_obstacles;
      _proposed_obstacles_type * proposed_obstacles;
      uint32_t proposed_obstacle_info_length;
      typedef mower_msgs::MapObstacleInfo _proposed_obstacle_info_type;
      _proposed_obstacle_info_type st_proposed_obstacle_info;
      _proposed_obstacle_info_type * proposed_obstacle_info;
      typedef uint32_t _id_type;
      _id_type id;

    MapArea():
      name(""),
      area(),
      obstacles_length(0), st_obstacles(), obstacles(nullptr),
      is_navigation_area(0),
      obstacle_info_length(0), st_obstacle_info(), obstacle_info(nullptr),
      proposed_obstacles_length(0), st_proposed_obstacles(), proposed_obstacles(nullptr),
      proposed_obstacle_info_length(0), st_proposed_obstacle_info(), proposed_obstacle_info(nullptr),
      id(0)
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      uint32_t length_name = strlen(this->name);
      varToArr(outbuffer + offset, length_name);
      offset += 4;
      memcpy(outbuffer + offset, this->name, length_name);
      offset += length_name;
      offset += this->area.serialize(outbuffer + offset);
      *(outbuffer + offset + 0) = (this->obstacles_length >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (this->obstacles_length >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (this->obstacles_length >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (this->obstacles_length >> (8 * 3)) & 0xFF;
      offset += sizeof(this->obstacles_length);
      for( uint32_t i = 0; i < obstacles_length; i++){
        offset += this->obstacles[i].serialize(outbuffer + offset);
      }
      union {
        bool real;
        uint8_t base;
      } u_is_navigation_area;
      u_is_navigation_area.real = this->is_navigation_area;
      *(outbuffer + offset + 0) = (u_is_navigation_area.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->is_navigation_area);
      *(outbuffer + offset + 0) = (this->obstacle_info_length >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (this->obstacle_info_length >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (this->obstacle_info_length >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (this->obstacle_info_length >> (8 * 3)) & 0xFF;
      offset += sizeof(this->obstacle_info_length);
      for( uint32_t i = 0; i < obstacle_info_length; i++){
        offset += this->obstacle_info[i].serialize(outbuffer + offset);
      }
      *(outbuffer + offset + 0) = (this->proposed_obstacles_length >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (this->proposed_obstacles_length >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (this->proposed_obstacles_length >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (this->proposed_obstacles_length >> (8 * 3)) & 0xFF;
      offset += sizeof(this->proposed_obstacles_length);
      for( uint32_t i = 0; i < proposed_obstacles_length; i++){
        offset += this->proposed_obstacles[i].serialize(outbuffer + offset);
      }
      *(outbuffer + offset + 0) = (this->proposed_obstacle_info_length >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (this->proposed_obstacle_info_length >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (this->proposed_obstacle_info_length >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (this->proposed_obstacle_info_length >> (8 * 3)) & 0xFF;
      offset += sizeof(this->proposed_obstacle_info_length);
      for( uint32_t i = 0; i < proposed_obstacle_info_length; i++){
        offset += this->proposed_obstacle_info[i].serialize(outbuffer + offset);
      }
      union {
        uint32_t real;
        uint32_t base;
      } u_id;
      u_id.real = this->id;
      *(outbuffer + offset + 0) = (u_id.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_id.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_id.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_id.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->id);
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      uint32_t length_name;
      arrToVar(length_name, (inbuffer + offset));
      offset += 4;
      for(unsigned int k= offset; k< offset+length_name; ++k){
          inbuffer[k-1]=inbuffer[k];
      }
      inbuffer[offset+length_name-1]=0;
      this->name = (char *)(inbuffer + offset-1);
      offset += length_name;
      offset += this->area.deserialize(inbuffer + offset);
      uint32_t obstacles_lengthT = ((uint32_t) (*(inbuffer + offset)));
      obstacles_lengthT |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      obstacles_lengthT |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      obstacles_lengthT |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      offset += sizeof(this->obstacles_length);
      if(obstacles_lengthT > obstacles_length)
        this->obstacles = (geometry_msgs::Polygon*)realloc(this->obstacles, obstacles_lengthT * sizeof(geometry_msgs::Polygon));
      obstacles_length = obstacles_lengthT;
      for( uint32_t i = 0; i < obstacles_length; i++){
        offset += this->obstacles[i].deserialize(inbuffer + offset);
      }
      union {
        bool real;
        uint8_t base;
      } u_is_navigation_area;
      u_is_navigation_area.base = 0;
      u_is_navigation_area.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->is_navigation_area = u_is_navigation_area.real;
      offset += sizeof(this->is_navigation_area);
      uint32_t obstacle_info_lengthT = ((uint32_t) (*(inbuffer + offset)));
      obstacle_info_lengthT |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      obstacle_info_lengthT |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      obstacle_info_lengthT |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      offset += sizeof(this->obstacle_info_length);
      if(obstacle_info_lengthT > obstacle_info_length)
        this->obstacle_info = (mower_msgs::MapObstacleInfo*)realloc(this->obstacle_info, obstacle_info_lengthT * sizeof(mower_msgs::MapObstacleInfo));
      obstacle_info_length = obstacle_info_lengthT;
      for( uint32_t i = 0; i < obstacle_info_length; i++){
        offset += this->obstacle_info[i].deserialize(inbuffer + offset);
      }
      uint32_t proposed_obstacles_lengthT = ((uint32_t) (*(inbuffer + offset)));
      proposed_obstacles_lengthT |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      proposed_obstacles_lengthT |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      proposed_obstacles_lengthT |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      offset += sizeof(this->proposed_obstacles_length);
      if(proposed_obstacles_lengthT > proposed_obstacles_length)
        this->proposed_obstacles = (geometry_msgs::Polygon*)realloc(this->proposed_obstacles, proposed_obstacles_lengthT * sizeof(geometry_msgs::Polygon));
      proposed_obstacles_length = proposed_obstacles_lengthT;
      for( uint32_t i = 0; i < proposed_obstacles_length; i++){
        offset += this->proposed_obstacles[i].deserialize(inbuffer + offset);
      }
      uint32_t proposed_obstacle_info_lengthT = ((uint32_t) (*(inbuffer + offset)));
      proposed_obstacle_info_lengthT |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      proposed_obstacle_info_lengthT |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      proposed_obstacle_info_lengthT |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      offset += sizeof(this->proposed_obstacle_info_length);
      if(proposed_obstacle_info_lengthT > proposed_obstacle_info_length)
        this->proposed_obstacle_info = (mower_msgs::MapObstacleInfo*)realloc(this->proposed_obstacle_info, proposed_obstacle_info_lengthT * sizeof(mower_msgs::MapObstacleInfo));
      proposed_obstacle_info_length = proposed_obstacle_info_lengthT;
      for( uint32_t i = 0; i < proposed_obstacle_info_length; i++){
        offset += this->proposed_obstacle_info[i].deserialize(inbuffer + offset);
      }
      union {
        uint32_t real;
        uint32_t base;
      } u_id;
      u_id.base = 0;
      u_id.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_id.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_id.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_id.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->id = u_id.real;
      offset += sizeof(this->id);
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/MapArea"; };
    virtual const char * getMD5() override { return "fbbf57e1749076ca19895b87d3012e25"; };

  };

}
#endif
