#ifndef _ROS_mower_msgs_MapObstacleInfo_h
#define _ROS_mower_msgs_MapObstacleInfo_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"

namespace mower_msgs
{

  class MapObstacleInfo : public ros::Msg
  {
    public:
      typedef const char* _name_type;
      _name_type name;
      typedef uint8_t _source_type;
      _source_type source;
      typedef bool _pending_type;
      _pending_type pending;
      typedef uint32_t _id_type;
      _id_type id;
      enum { SOURCE_USER = 0        # drawn by the operator in the GUI / imported };
      enum { SOURCE_TRACKER = 1     # promoted from an /obstacle_tracker observation };
      enum { SOURCE_DIG = 2         # proposed by the wheel-slip dig detector };

    MapObstacleInfo():
      name(""),
      source(0),
      pending(0),
      id(0)
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      uint32_t length_name = strlen(this->name);
      varToArr(outbuffer + offset, length_name);
      offset += 4;
      memcpy(outbuffer + offset, this->name, length_name);
      offset += length_name;
      *(outbuffer + offset + 0) = (this->source >> (8 * 0)) & 0xFF;
      offset += sizeof(this->source);
      union {
        bool real;
        uint8_t base;
      } u_pending;
      u_pending.real = this->pending;
      *(outbuffer + offset + 0) = (u_pending.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->pending);
      union {
        uint32_t real;
        uint32_t base;
      } u_id;
      u_id.real = this->id;
      *(outbuffer + offset + 0) = (u_id.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_id.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_id.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_id.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->id);
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      uint32_t length_name;
      arrToVar(length_name, (inbuffer + offset));
      offset += 4;
      for(unsigned int k= offset; k< offset+length_name; ++k){
          inbuffer[k-1]=inbuffer[k];
      }
      inbuffer[offset+length_name-1]=0;
      this->name = (char *)(inbuffer + offset-1);
      offset += length_name;
      this->source =  ((uint8_t) (*(inbuffer + offset)));
      offset += sizeof(this->source);
      union {
        bool real;
        uint8_t base;
      } u_pending;
      u_pending.base = 0;
      u_pending.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->pending = u_pending.real;
      offset += sizeof(this->pending);
      union {
        uint32_t real;
        uint32_t base;
      } u_id;
      u_id.base = 0;
      u_id.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_id.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_id.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_id.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->id = u_id.real;
      offset += sizeof(this->id);
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/MapObstacleInfo"; };
    virtual const char * getMD5() override { return "83d92c71b77c2e4abf9faf4a4ee11b52"; };

  };

}
#endif
