#ifndef _ROS_mower_msgs_ObstacleArray_h
#define _ROS_mower_msgs_ObstacleArray_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"
#include "mower_msgs/TrackedObstacle.h"
#include "std_msgs/Header.h"

namespace mower_msgs
{

  class ObstacleArray : public ros::Msg
  {
    public:
      typedef std_msgs::Header _header_type;
      _header_type header;
      uint32_t obstacles_length;
      typedef mower_msgs::TrackedObstacle _obstacles_type;
      _obstacles_type st_obstacles;
      _obstacles_type * obstacles;

    ObstacleArray():
      header(),
      obstacles_length(0), st_obstacles(), obstacles(nullptr)
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      offset += this->header.serialize(outbuffer + offset);
      *(outbuffer + offset + 0) = (this->obstacles_length >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (this->obstacles_length >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (this->obstacles_length >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (this->obstacles_length >> (8 * 3)) & 0xFF;
      offset += sizeof(this->obstacles_length);
      for( uint32_t i = 0; i < obstacles_length; i++){
        offset += this->obstacles[i].serialize(outbuffer + offset);
      }
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      offset += this->header.deserialize(inbuffer + offset);
      uint32_t obstacles_lengthT = ((uint32_t) (*(inbuffer + offset)));
      obstacles_lengthT |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      obstacles_lengthT |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      obstacles_lengthT |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      offset += sizeof(this->obstacles_length);
      if(obstacles_lengthT > obstacles_length)
        this->obstacles = (mower_msgs::TrackedObstacle*)realloc(this->obstacles, obstacles_lengthT * sizeof(mower_msgs::TrackedObstacle));
      obstacles_length = obstacles_lengthT;
      for( uint32_t i = 0; i < obstacles_length; i++){
        offset += this->obstacles[i].deserialize(inbuffer + offset);
      }
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/ObstacleArray"; };
    virtual const char * getMD5() override { return "35e9288248a95eff75c204bb93a8b5bc"; };

  };

}
#endif
