#ifndef _ROS_mower_msgs_RecordedAreaPolygon_h
#define _ROS_mower_msgs_RecordedAreaPolygon_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"
#include "geometry_msgs/Polygon.h"

namespace mower_msgs
{

  class RecordedAreaPolygon : public ros::Msg
  {
    public:
      typedef geometry_msgs::Polygon _area_type;
      _area_type area;

    RecordedAreaPolygon():
      area()
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      offset += this->area.serialize(outbuffer + offset);
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      offset += this->area.deserialize(inbuffer + offset);
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/RecordedAreaPolygon"; };
    virtual const char * getMD5() override { return "ba100c4de9b5bc002b3fc9a295a90c17"; };

  };

}
#endif
