#ifndef _ROS_mower_msgs_RecordedAreaPolygonArray_h
#define _ROS_mower_msgs_RecordedAreaPolygonArray_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"
#include "mower_msgs/RecordedAreaPolygon.h"
#include "std_msgs/Header.h"

namespace mower_msgs
{

  class RecordedAreaPolygonArray : public ros::Msg
  {
    public:
      typedef std_msgs::Header _header_type;
      _header_type header;
      uint32_t areas_length;
      typedef mower_msgs::RecordedAreaPolygon _areas_type;
      _areas_type st_areas;
      _areas_type * areas;

    RecordedAreaPolygonArray():
      header(),
      areas_length(0), st_areas(), areas(nullptr)
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      offset += this->header.serialize(outbuffer + offset);
      *(outbuffer + offset + 0) = (this->areas_length >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (this->areas_length >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (this->areas_length >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (this->areas_length >> (8 * 3)) & 0xFF;
      offset += sizeof(this->areas_length);
      for( uint32_t i = 0; i < areas_length; i++){
        offset += this->areas[i].serialize(outbuffer + offset);
      }
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      offset += this->header.deserialize(inbuffer + offset);
      uint32_t areas_lengthT = ((uint32_t) (*(inbuffer + offset)));
      areas_lengthT |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      areas_lengthT |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      areas_lengthT |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      offset += sizeof(this->areas_length);
      if(areas_lengthT > areas_length)
        this->areas = (mower_msgs::RecordedAreaPolygon*)realloc(this->areas, areas_lengthT * sizeof(mower_msgs::RecordedAreaPolygon));
      areas_length = areas_lengthT;
      for( uint32_t i = 0; i < areas_length; i++){
        offset += this->areas[i].deserialize(inbuffer + offset);
      }
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/RecordedAreaPolygonArray"; };
    virtual const char * getMD5() override { return "5e0ad3247ba5f37d607c706e9c9268e3"; };

  };

}
#endif
