#ifndef _ROS_mower_msgs_TrackedObstacle_h
#define _ROS_mower_msgs_TrackedObstacle_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"
#include "geometry_msgs/Point.h"
#include "geometry_msgs/Polygon.h"
#include "ros/time.h"

namespace mower_msgs
{

  class TrackedObstacle : public ros::Msg
  {
    public:
      typedef uint32_t _id_type;
      _id_type id;
      typedef geometry_msgs::Polygon _polygon_type;
      _polygon_type polygon;
      typedef geometry_msgs::Point _centroid_type;
      _centroid_type centroid;
      typedef double _radius_type;
      _radius_type radius;
      typedef ros::Time _first_seen_type;
      _first_seen_type first_seen;
      typedef uint32_t _observation_count_type;
      _observation_count_type observation_count;
      typedef uint8_t _status_type;
      _status_type status;
      enum { TRANSIENT = 0 };
      enum { PERSISTENT = 1 };

    TrackedObstacle():
      id(0),
      polygon(),
      centroid(),
      radius(0),
      first_seen(),
      observation_count(0),
      status(0)
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      union {
        uint32_t real;
        uint32_t base;
      } u_id;
      u_id.real = this->id;
      *(outbuffer + offset + 0) = (u_id.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_id.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_id.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_id.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->id);
      offset += this->polygon.serialize(outbuffer + offset);
      offset += this->centroid.serialize(outbuffer + offset);
      union {
        double real;
        uint64_t base;
      } u_radius;
      u_radius.real = this->radius;
      *(outbuffer + offset + 0) = (u_radius.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_radius.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_radius.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_radius.base >> (8 * 3)) & 0xFF;
      *(outbuffer + offset + 4) = (u_radius.base >> (8 * 4)) & 0xFF;
      *(outbuffer + offset + 5) = (u_radius.base >> (8 * 5)) & 0xFF;
      *(outbuffer + offset + 6) = (u_radius.base >> (8 * 6)) & 0xFF;
      *(outbuffer + offset + 7) = (u_radius.base >> (8 * 7)) & 0xFF;
      offset += sizeof(this->radius);
      offset += this->first_seen.serialize(outbuffer + offset);
      union {
        uint32_t real;
        uint32_t base;
      } u_observation_count;
      u_observation_count.real = this->observation_count;
      *(outbuffer + offset + 0) = (u_observation_count.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_observation_count.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_observation_count.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_observation_count.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->observation_count);
      *(outbuffer + offset + 0) = (this->status >> (8 * 0)) & 0xFF;
      offset += sizeof(this->status);
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      union {
        uint32_t real;
        uint32_t base;
      } u_id;
      u_id.base = 0;
      u_id.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_id.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_id.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_id.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->id = u_id.real;
      offset += sizeof(this->id);
      offset += this->polygon.deserialize(inbuffer + offset);
      offset += this->centroid.deserialize(inbuffer + offset);
      union {
        double real;
        uint64_t base;
      } u_radius;
      u_radius.base = 0;
      u_radius.base |= ((uint64_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_radius.base |= ((uint64_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_radius.base |= ((uint64_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_radius.base |= ((uint64_t) (*(inbuffer + offset + 3))) << (8 * 3);
      u_radius.base |= ((uint64_t) (*(inbuffer + offset + 4))) << (8 * 4);
      u_radius.base |= ((uint64_t) (*(inbuffer + offset + 5))) << (8 * 5);
      u_radius.base |= ((uint64_t) (*(inbuffer + offset + 6))) << (8 * 6);
      u_radius.base |= ((uint64_t) (*(inbuffer + offset + 7))) << (8 * 7);
      this->radius = u_radius.real;
      offset += sizeof(this->radius);
      offset += this->first_seen.deserialize(inbuffer + offset);
      union {
        uint32_t real;
        uint32_t base;
      } u_observation_count;
      u_observation_count.base = 0;
      u_observation_count.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_observation_count.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_observation_count.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_observation_count.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->observation_count = u_observation_count.real;
      offset += sizeof(this->observation_count);
      this->status =  ((uint8_t) (*(inbuffer + offset)));
      offset += sizeof(this->status);
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/TrackedObstacle"; };
    virtual const char * getMD5() override { return "665322b2e971c75a49805409b3280db3"; };

  };

}
#endif
