#ifndef _ROS_mower_msgs_WheelTick_h
#define _ROS_mower_msgs_WheelTick_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"
#include "ros/time.h"

namespace mower_msgs
{

  class WheelTick : public ros::Msg
  {
    public:
      typedef ros::Time _stamp_type;
      _stamp_type stamp;
      typedef float _wheel_tick_factor_type;
      _wheel_tick_factor_type wheel_tick_factor;
      typedef uint8_t _valid_wheels_type;
      _valid_wheels_type valid_wheels;
      typedef uint8_t _wheel_direction_fl_type;
      _wheel_direction_fl_type wheel_direction_fl;
      typedef uint32_t _wheel_ticks_fl_type;
      _wheel_ticks_fl_type wheel_ticks_fl;
      typedef uint8_t _wheel_direction_fr_type;
      _wheel_direction_fr_type wheel_direction_fr;
      typedef uint32_t _wheel_ticks_fr_type;
      _wheel_ticks_fr_type wheel_ticks_fr;
      typedef uint8_t _wheel_direction_rl_type;
      _wheel_direction_rl_type wheel_direction_rl;
      typedef uint32_t _wheel_ticks_rl_type;
      _wheel_ticks_rl_type wheel_ticks_rl;
      typedef uint8_t _wheel_direction_rr_type;
      _wheel_direction_rr_type wheel_direction_rr;
      typedef uint32_t _wheel_ticks_rr_type;
      _wheel_ticks_rr_type wheel_ticks_rr;
      enum { WHEEL_VALID_FL = 1 };
      enum { WHEEL_VALID_FR = 2 };
      enum { WHEEL_VALID_RL = 4 };
      enum { WHEEL_VALID_RR = 8 };

    WheelTick():
      stamp(),
      wheel_tick_factor(0),
      valid_wheels(0),
      wheel_direction_fl(0),
      wheel_ticks_fl(0),
      wheel_direction_fr(0),
      wheel_ticks_fr(0),
      wheel_direction_rl(0),
      wheel_ticks_rl(0),
      wheel_direction_rr(0),
      wheel_ticks_rr(0)
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      offset += this->stamp.serialize(outbuffer + offset);
      union {
        float real;
        uint32_t base;
      } u_wheel_tick_factor;
      u_wheel_tick_factor.real = this->wheel_tick_factor;
      *(outbuffer + offset + 0) = (u_wheel_tick_factor.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_wheel_tick_factor.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_wheel_tick_factor.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_wheel_tick_factor.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->wheel_tick_factor);
      *(outbuffer + offset + 0) = (this->valid_wheels >> (8 * 0)) & 0xFF;
      offset += sizeof(this->valid_wheels);
      *(outbuffer + offset + 0) = (this->wheel_direction_fl >> (8 * 0)) & 0xFF;
      offset += sizeof(this->wheel_direction_fl);
      union {
        uint32_t real;
        uint32_t base;
      } u_wheel_ticks_fl;
      u_wheel_ticks_fl.real = this->wheel_ticks_fl;
      *(outbuffer + offset + 0) = (u_wheel_ticks_fl.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_wheel_ticks_fl.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_wheel_ticks_fl.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_wheel_ticks_fl.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->wheel_ticks_fl);
      *(outbuffer + offset + 0) = (this->wheel_direction_fr >> (8 * 0)) & 0xFF;
      offset += sizeof(this->wheel_direction_fr);
      union {
        uint32_t real;
        uint32_t base;
      } u_wheel_ticks_fr;
      u_wheel_ticks_fr.real = this->wheel_ticks_fr;
      *(outbuffer + offset + 0) = (u_wheel_ticks_fr.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_wheel_ticks_fr.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_wheel_ticks_fr.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_wheel_ticks_fr.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->wheel_ticks_fr);
      *(outbuffer + offset + 0) = (this->wheel_direction_rl >> (8 * 0)) & 0xFF;
      offset += sizeof(this->wheel_direction_rl);
      union {
        uint32_t real;
        uint32_t base;
      } u_wheel_ticks_rl;
      u_wheel_ticks_rl.real = this->wheel_ticks_rl;
      *(outbuffer + offset + 0) = (u_wheel_ticks_rl.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_wheel_ticks_rl.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_wheel_ticks_rl.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_wheel_ticks_rl.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->wheel_ticks_rl);
      *(outbuffer + offset + 0) = (this->wheel_direction_rr >> (8 * 0)) & 0xFF;
      offset += sizeof(this->wheel_direction_rr);
      union {
        uint32_t real;
        uint32_t base;
      } u_wheel_ticks_rr;
      u_wheel_ticks_rr.real = this->wheel_ticks_rr;
      *(outbuffer + offset + 0) = (u_wheel_ticks_rr.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_wheel_ticks_rr.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_wheel_ticks_rr.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_wheel_ticks_rr.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->wheel_ticks_rr);
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      offset += this->stamp.deserialize(inbuffer + offset);
      union {
        float real;
        uint32_t base;
      } u_wheel_tick_factor;
      u_wheel_tick_factor.base = 0;
      u_wheel_tick_factor.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_wheel_tick_factor.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_wheel_tick_factor.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_wheel_tick_factor.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->wheel_tick_factor = u_wheel_tick_factor.real;
      offset += sizeof(this->wheel_tick_factor);
      this->valid_wheels =  ((uint8_t) (*(inbuffer + offset)));
      offset += sizeof(this->valid_wheels);
      this->wheel_direction_fl =  ((uint8_t) (*(inbuffer + offset)));
      offset += sizeof(this->wheel_direction_fl);
      union {
        uint32_t real;
        uint32_t base;
      } u_wheel_ticks_fl;
      u_wheel_ticks_fl.base = 0;
      u_wheel_ticks_fl.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_wheel_ticks_fl.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_wheel_ticks_fl.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_wheel_ticks_fl.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->wheel_ticks_fl = u_wheel_ticks_fl.real;
      offset += sizeof(this->wheel_ticks_fl);
      this->wheel_direction_fr =  ((uint8_t) (*(inbuffer + offset)));
      offset += sizeof(this->wheel_direction_fr);
      union {
        uint32_t real;
        uint32_t base;
      } u_wheel_ticks_fr;
      u_wheel_ticks_fr.base = 0;
      u_wheel_ticks_fr.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_wheel_ticks_fr.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_wheel_ticks_fr.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_wheel_ticks_fr.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->wheel_ticks_fr = u_wheel_ticks_fr.real;
      offset += sizeof(this->wheel_ticks_fr);
      this->wheel_direction_rl =  ((uint8_t) (*(inbuffer + offset)));
      offset += sizeof(this->wheel_direction_rl);
      union {
        uint32_t real;
        uint32_t base;
      } u_wheel_ticks_rl;
      u_wheel_ticks_rl.base = 0;
      u_wheel_ticks_rl.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_wheel_ticks_rl.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_wheel_ticks_rl.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_wheel_ticks_rl.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->wheel_ticks_rl = u_wheel_ticks_rl.real;
      offset += sizeof(this->wheel_ticks_rl);
      this->wheel_direction_rr =  ((uint8_t) (*(inbuffer + offset)));
      offset += sizeof(this->wheel_direction_rr);
      union {
        uint32_t real;
        uint32_t base;
      } u_wheel_ticks_rr;
      u_wheel_ticks_rr.base = 0;
      u_wheel_ticks_rr.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_wheel_ticks_rr.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_wheel_ticks_rr.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_wheel_ticks_rr.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->wheel_ticks_rr = u_wheel_ticks_rr.real;
      offset += sizeof(this->wheel_ticks_rr);
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/WheelTick"; };
    virtual const char * getMD5() override { return "0a456294b4f707f3dbae296410dccae4"; };

  };

}
#endif
