// Code generated by generate_go_msgs.sh — DO NOT EDIT.
package sensor

import (
	"github.com/mowglinext/mowglinext/pkg/msgs/geometry"
)

// Imu matches sensor_msgs/msg/Imu.
type Imu struct {
	Header                    geometry.Header                `json:"header"`
	Orientation               geometry.Quaternion            `json:"orientation"`
	OrientationCovariance     [9]float64                     `json:"orientation_covariance"`
	AngularVelocity           geometry.Vector3               `json:"angular_velocity"`
	AngularVelocityCovariance [9]float64                     `json:"angular_velocity_covariance"`
	LinearAcceleration        geometry.Vector3               `json:"linear_acceleration"`
	LinearAccelerationCovariance [9]float64                     `json:"linear_acceleration_covariance"`
}

// LaserScan matches sensor_msgs/msg/LaserScan.
type LaserScan struct {
	Header                    geometry.Header                `json:"header"`
	AngleMin                  float32                        `json:"angle_min"`
	AngleMax                  float32                        `json:"angle_max"`
	AngleIncrement            float32                        `json:"angle_increment"`
	TimeIncrement             float32                        `json:"time_increment"`
	ScanTime                  float32                        `json:"scan_time"`
	RangeMin                  float32                        `json:"range_min"`
	RangeMax                  float32                        `json:"range_max"`
	Ranges                    []float32                      `json:"ranges"`
	Intensities               []float32                      `json:"intensities"`
}

// NavSatFix matches sensor_msgs/msg/NavSatFix.
type NavSatFix struct {
	Header                    geometry.Header                `json:"header"`
	Status                    NavSatStatus                   `json:"status"`
	Latitude                  float64                        `json:"latitude"`
	Longitude                 float64                        `json:"longitude"`
	Altitude                  float64                        `json:"altitude"`
	PositionCovariance        [9]float64                     `json:"position_covariance"`
	PositionCovarianceType    uint8                          `json:"position_covariance_type"`
}

// NavSatStatus matches sensor_msgs/msg/NavSatStatus.
type NavSatStatus struct {
	Status                    int8                           `json:"status"`
	Service                   uint16                         `json:"service"`
}

