// Code generated by generate_go_msgs.sh — DO NOT EDIT.
package std

import (
	"github.com/mowglinext/mowglinext/pkg/msgs/geometry"
)

// Bool matches std_msgs/msg/Bool.
type Bool struct {
	Data                      bool                           `json:"data"`
}

// ColorRGBA matches std_msgs/msg/ColorRGBA.
type ColorRGBA struct {
	R                         float32                        `json:"r"`
	G                         float32                        `json:"g"`
	B                         float32                        `json:"b"`
	A                         float32                        `json:"a"`
}

// Header matches std_msgs/msg/Header.
type Header struct {
	Stamp                     geometry.Stamp                 `json:"stamp"`
	FrameId                   string                         `json:"frame_id"`
}

// String matches std_msgs/msg/String.
type String struct {
	Data                      string                         `json:"data"`
}

