#!/usr/bin/env bash
# =============================================================================
# MowgliNext — One-line installer bootstrap
#
# This script is served at https://mowgli.garden/install.sh and accepts
# hardware configuration flags from the web composer. It validates and
# forwards only the current Universal GNSS/runtime installer switches.
#
# Usage (generated by the composer at mowgli.garden):
#   curl -sSL https://mowgli.garden/install.sh | bash -s -- \
#     --gnss-receiver-family=auto --gnss-connection=uart \
#     --lidar=ldlidar-uart
#
# Or run the fully interactive installer (no flags):
#   curl -sSL https://mowgli.garden/install.sh | bash
# =============================================================================

set -euo pipefail

# ── Colours ────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

info()  { echo -e "  ${GREEN}OK${NC}  $*"; }
warn()  { echo -e "  ${YELLOW}!!${NC}  $*"; }
error() { echo -e "${RED}[x]${NC} $*" >&2; }
step()  { echo -e "\n${CYAN}${BOLD}── $* ──${NC}"; }

repo_has_local_changes() {
  local repo_dir="${1:?repo_has_local_changes: missing repo dir}"
  [ -n "$(git -C "$repo_dir" status --porcelain --untracked-files=all 2>/dev/null || true)" ]
}

repo_current_branch() {
  local repo_dir="${1:?repo_current_branch: missing repo dir}"
  git -C "$repo_dir" symbolic-ref --quiet --short HEAD 2>/dev/null || printf 'detached\n'
}

update_existing_repo_checkout() {
  local repo_dir="${1:?update_existing_repo_checkout: missing repo dir}"
  local current_branch
  local local_head
  local remote_head

  info "Found existing git repository at $repo_dir"

  if repo_has_local_changes "$repo_dir"; then
    warn "Local changes detected in $repo_dir — skipping bootstrap git update."
    return 0
  fi

  current_branch="$(repo_current_branch "$repo_dir")"
  if [ "$current_branch" != "$REPO_BRANCH" ]; then
    warn "Repository is on '$current_branch'; bootstrap will not switch to '$REPO_BRANCH' automatically."
    return 0
  fi

  if ! git -C "$repo_dir" fetch --quiet origin "$REPO_BRANCH"; then
    warn "Could not fetch origin/$REPO_BRANCH — continuing with the current checkout."
    return 0
  fi

  if ! git -C "$repo_dir" rev-parse --verify "refs/remotes/origin/$REPO_BRANCH" >/dev/null 2>&1; then
    warn "Remote branch origin/$REPO_BRANCH is unavailable after fetch — continuing with the current checkout."
    return 0
  fi

  local_head="$(git -C "$repo_dir" rev-parse HEAD 2>/dev/null || true)"
  remote_head="$(git -C "$repo_dir" rev-parse "origin/$REPO_BRANCH" 2>/dev/null || true)"
  if [ -n "$local_head" ] && [ "$local_head" = "$remote_head" ]; then
    info "Existing installation is already up to date"
    return 0
  fi

  if git -C "$repo_dir" merge --ff-only "origin/$REPO_BRANCH" >/dev/null 2>&1; then
    info "Fast-forwarded existing installation to origin/$REPO_BRANCH"
    return 0
  fi

  warn "Existing checkout is not a clean fast-forward to origin/$REPO_BRANCH — continuing without updating."
}

# ── Defaults ───────────────────────────────────────────────────────────────
GNSS_FLAG=""
GNSS_RECEIVER_FAMILY_FLAG=""
GNSS_CONNECTION_FLAG=""
LIDAR_FLAG=""
TFLUNA_FLAG=""
BACKEND_FLAG=""
IMAGE_TAG_FLAG=""

REPO_URL="https://github.com/mowglinext/mowglinext.git"
REPO_BRANCH="main"
INSTALL_DIR="${MOWGLI_HOME:-$HOME/mowglinext}"

# ── Parse flags ────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --backend=*) BACKEND_FLAG="${1#--backend=}"; shift ;;
    --gnss=*)    GNSS_FLAG="${1#--gnss=}"; shift ;;
    --gnss-connection=*) GNSS_CONNECTION_FLAG="${1#--gnss-connection=}"; shift ;;
    --gnss-receiver-family=*) GNSS_RECEIVER_FAMILY_FLAG="${1#--gnss-receiver-family=}"; shift ;;
    --gps=*)
      warn "Deprecated bootstrap flag '$1' detected — normalizing to the Universal GNSS installer contract."
      case "${1#--gps=}" in
        ubx-usb)
          GNSS_FLAG="${GNSS_FLAG:-ublox}"
          GNSS_CONNECTION_FLAG="${GNSS_CONNECTION_FLAG:-usb}"
          ;;
        ubx-uart)
          GNSS_FLAG="${GNSS_FLAG:-ublox}"
          GNSS_CONNECTION_FLAG="${GNSS_CONNECTION_FLAG:-uart}"
          ;;
        nmea-usb)
          if [[ -n "$GNSS_FLAG" && "$GNSS_FLAG" != "auto" && "$GNSS_FLAG" != "gps" ]]; then
            warn "Ignoring deprecated NMEA preset because an explicit --gnss=$GNSS_FLAG selection is already present."
          else
            GNSS_RECEIVER_FAMILY_FLAG="${GNSS_RECEIVER_FAMILY_FLAG:-nmea}"
          fi
          GNSS_CONNECTION_FLAG="${GNSS_CONNECTION_FLAG:-usb}"
          ;;
        nmea-uart)
          if [[ -n "$GNSS_FLAG" && "$GNSS_FLAG" != "auto" && "$GNSS_FLAG" != "gps" ]]; then
            warn "Ignoring deprecated NMEA preset because an explicit --gnss=$GNSS_FLAG selection is already present."
          else
            GNSS_RECEIVER_FAMILY_FLAG="${GNSS_RECEIVER_FAMILY_FLAG:-nmea}"
          fi
          GNSS_CONNECTION_FLAG="${GNSS_CONNECTION_FLAG:-uart}"
          ;;
        *)
          warn "Unknown deprecated GPS preset: ${1#--gps=} — ignoring it and continuing with Universal GNSS defaults."
          ;;
      esac
      shift
      ;;
    --lidar=*)   LIDAR_FLAG="${1#--lidar=}"; shift ;;
    --tfluna=*)  TFLUNA_FLAG="${1#--tfluna=}"; shift ;;  # deprecated, kept for backward compat
    --branch=*)  REPO_BRANCH="${1#--branch=}"; shift ;;
    --image-tag=*) IMAGE_TAG_FLAG="${1#--image-tag=}"; shift ;;
    --help|-h)
      echo "Usage: curl -sSL https://mowgli.garden/install.sh | bash -s -- [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --backend=TYPE      Hardware backend: mowgli (default), mavros (advanced Pixhawk path)"
      echo "  --gnss-receiver-family"
      echo "                     Universal GNSS receiver family first-boot default: auto, ublox, unicore, nmea"
      echo "  --gnss-connection  Universal GNSS serial link first-boot default: usb or uart"
      echo "                     (the installer still asks for the actual device path and baud; active runtime GNSS config later lives in YAML/GUI)"
      echo "  --lidar=PRESET     LiDAR config: none, ldlidar-usb, ldlidar-uart,"
      echo "                     rplidar-usb, rplidar-uart, stl27l-usb, stl27l-uart"
      echo "  --branch=BRANCH    Git branch (default: main)"
      echo "  --image-tag=TAG    Container image tag/channel for the installer"
      echo ""
      echo "Without flags, the full interactive installer runs."
      exit 0
      ;;
    *)
      warn "Unknown option: $1"
      shift
      ;;
  esac
done

# ── Banner ─────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}"
echo '  __  __                  _ _ _  _  _           _   '
echo ' |  \/  | _____      __ | (_) \| || | _____  _| |_ '
echo ' | |\/| |/ _ \ \ /\ / / | | |  \  |/ _ \ \/ / __|'
echo ' | |  | | (_) \ V  V /  | | | |\  |  __/>  <| |_  '
echo ' |_|  |_|\___/ \_/\_/   |_|_|_| \_|\___/_/\_\\__|'
echo -e "${NC}"
echo -e "${DIM}  Open-source autonomous robot mower — mowgli.garden${NC}"
echo ""

# ── Prerequisite: git ──────────────────────────────────────────────────────
if ! command -v git &>/dev/null; then
  step "Installing git"
  if command -v apt-get &>/dev/null; then
    sudo apt-get update -qq && sudo apt-get install -y -qq git
  elif command -v dnf &>/dev/null; then
    sudo dnf install -y git
  else
    error "git is required but not found. Please install git first."
    exit 1
  fi
  info "git installed"
fi

# ── Clone / update repo ───────────────────────────────────────────────────
step "Preparing MowgliNext"

if [ -d "$INSTALL_DIR/.git" ]; then
  update_existing_repo_checkout "$INSTALL_DIR"
elif [ -d "$INSTALL_DIR" ]; then
  warn "$INSTALL_DIR exists but is not a git repo — backing up"
  mv "$INSTALL_DIR" "${INSTALL_DIR}.bak.$(date +%s)"
  git clone --branch "$REPO_BRANCH" --depth 1 "$REPO_URL" "$INSTALL_DIR"
  info "Cloned to $INSTALL_DIR"
else
  git clone --branch "$REPO_BRANCH" --depth 1 "$REPO_URL" "$INSTALL_DIR"
  info "Cloned to $INSTALL_DIR"
fi

# ── Hand off to the full installer ─────────────────────────────────────────
step "Launching installer"

INSTALLER="$INSTALL_DIR/install/mowglinext.sh"

if [ ! -f "$INSTALLER" ]; then
  error "Installer not found at $INSTALLER"
  error "The repository may be incomplete. Try deleting $INSTALL_DIR and running again."
  exit 1
fi

chmod +x "$INSTALLER"

INSTALLER_ARGS=()
INSTALLER_ARGS+=("--branch=$REPO_BRANCH")
[[ -n "$IMAGE_TAG_FLAG" ]] && INSTALLER_ARGS+=("--image-tag=$IMAGE_TAG_FLAG")

HAS_INSTALLER_PRESET_ARGS=false

if [[ -n "$BACKEND_FLAG" ]]; then
  case "$BACKEND_FLAG" in
    mowgli|mavros)
      INSTALLER_ARGS+=("--backend=$BACKEND_FLAG")
      HAS_INSTALLER_PRESET_ARGS=true
      info "Hardware backend: $BACKEND_FLAG"
      ;;
    *)
      warn "Unknown hardware backend: $BACKEND_FLAG (expected mowgli|mavros) — installer will ask interactively"
      ;;
  esac
fi

if [[ -n "$GNSS_FLAG" ]]; then
  case "$GNSS_FLAG" in
    auto|gps)
      INSTALLER_ARGS+=("--gnss=auto")
      HAS_INSTALLER_PRESET_ARGS=true
      info "Universal GNSS receiver selection: auto"
      ;;
    ublox|unicore)
      INSTALLER_ARGS+=("--gnss=$GNSS_FLAG")
      HAS_INSTALLER_PRESET_ARGS=true
      info "Universal GNSS receiver selection: $GNSS_FLAG"
      ;;
    legacy)
      warn "Deprecated GNSS preset '$GNSS_FLAG' ignored — Universal GNSS is the only supported direct GNSS runtime."
      ;;
    *)
      warn "Unknown GNSS preset: $GNSS_FLAG (expected auto|ublox|unicore) — installer will ask interactively"
      ;;
  esac
fi

if [[ -n "$GNSS_RECEIVER_FAMILY_FLAG" ]]; then
  if [[ -n "$GNSS_FLAG" && "$GNSS_FLAG" != "auto" && "$GNSS_FLAG" != "gps" && "$GNSS_RECEIVER_FAMILY_FLAG" != "$GNSS_FLAG" ]]; then
    warn "Ignoring --gnss-receiver-family=$GNSS_RECEIVER_FAMILY_FLAG because --gnss=$GNSS_FLAG already selects the Universal GNSS receiver family."
  else
  case "$GNSS_RECEIVER_FAMILY_FLAG" in
    auto|ublox|unicore|nmea)
      INSTALLER_ARGS+=("--gnss-receiver-family=$GNSS_RECEIVER_FAMILY_FLAG")
      HAS_INSTALLER_PRESET_ARGS=true
      info "Universal GNSS receiver family override: $GNSS_RECEIVER_FAMILY_FLAG"
      ;;
    *)
      warn "Unknown GNSS receiver family override: $GNSS_RECEIVER_FAMILY_FLAG (expected auto|ublox|unicore|nmea) — installer will ask interactively"
      ;;
  esac
  fi
fi

if [[ -n "$GNSS_CONNECTION_FLAG" ]]; then
  case "$GNSS_CONNECTION_FLAG" in
    usb|uart)
      INSTALLER_ARGS+=("--gnss-connection=$GNSS_CONNECTION_FLAG")
      HAS_INSTALLER_PRESET_ARGS=true
      info "Universal GNSS serial connection: $GNSS_CONNECTION_FLAG"
      ;;
    *)
      warn "Unknown GNSS connection: $GNSS_CONNECTION_FLAG (expected usb|uart) — installer will ask interactively"
      ;;
  esac
fi

if [[ -n "$LIDAR_FLAG" ]]; then
  case "$LIDAR_FLAG" in
    none|ldlidar-usb|ldlidar-uart|rplidar-usb|rplidar-uart|stl27l-usb|stl27l-uart)
      INSTALLER_ARGS+=("--lidar=$LIDAR_FLAG")
      HAS_INSTALLER_PRESET_ARGS=true
      info "LiDAR: $LIDAR_FLAG"
      ;;
    *)
      warn "Unknown LiDAR preset: $LIDAR_FLAG — installer will ask interactively"
      ;;
  esac
fi

if [[ -n "$TFLUNA_FLAG" ]]; then
  case "$TFLUNA_FLAG" in
    none|front|edge|both)
      INSTALLER_ARGS+=("--tfluna=$TFLUNA_FLAG")
      HAS_INSTALLER_PRESET_ARGS=true
      info "Rangefinders: $TFLUNA_FLAG"
      ;;
    *)
      warn "Unknown TF-Luna preset: $TFLUNA_FLAG — installer will ask interactively"
      ;;
  esac
fi

echo ""
if $HAS_INSTALLER_PRESET_ARGS; then
  info "Hardware options forwarded to the installer — matching prompts will be skipped or defaulted."
else
  info "No hardware options forwarded — running fully interactive installer."
fi
echo ""

# Reattach stdin to the controlling terminal — when invoked as
# `curl ... | bash`, stdin is the pipe and `read` prompts in the
# interactive installer would otherwise return immediately.
if tty -s && [ -r /dev/tty ]; then
  exec bash "$INSTALLER" "${INSTALLER_ARGS[@]+"${INSTALLER_ARGS[@]}"}" </dev/tty
else
  warn "No /dev/tty available — interactive prompts may not work."
  exec bash "$INSTALLER" "${INSTALLER_ARGS[@]+"${INSTALLER_ARGS[@]}"}"
fi
