import js from '@eslint/js'
import tsPlugin from '@typescript-eslint/eslint-plugin'
import tsParser from '@typescript-eslint/parser'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'

// Flat config, replacing the ESLint 8-era `.eslintrc.cjs`.
//
// ESLint 9 does not read `.eslintrc.*` at all, so `yarn lint` had been failing
// with "ESLint couldn't find an eslint.config.(js|mjs|cjs) file" — zero files
// analysed — which is why this file exists. Do NOT bring `.eslintrc.cjs` back
// and do NOT set `ESLINT_USE_FLAT_CONFIG=false`: the eslintrc loader is CJS and
// cannot `require()` eslint-plugin-react-refresh (ESM-only since 0.5), so every
// linted file gains a phantom "Definition for rule
// 'react-refresh/only-export-components' was not found" error.

export default [
  {
    // `src/types/ros.generated.ts` is machine-generated
    // ("// Code generated by generate_ts_types.sh — DO NOT EDIT.") and
    // .github/workflows/msg-codegen-drift.yml runs `git diff --exit-code` on
    // it. A hand-fix would be reverted by the next regeneration AND fail that
    // gate, so it must be ignored rather than fixed.
    // `src/api/Api.ts` needs no entry — its own blanket `/* eslint-disable */`
    // already yields zero reported problems.
    ignores: ['dist/**', 'src/types/ros.generated.ts'],
  },

  js.configs.recommended,
  ...tsPlugin.configs['flat/recommended-type-checked'],

  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      parser: tsParser,
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: {
        // Flat-config replacement for `project: true` + `tsconfigRootDir:
        // __dirname`. tsconfig.json only includes `src`, so keep the lint
        // target as `src`; widening it needs a tsconfig change first.
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    linterOptions: {
      reportUnusedDisableDirectives: true,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },

  // -- Overlay C -- the debt ratchet ----------------------------------------
  // The ONE place a real rule is demoted, and the only reason `yarn lint` can
  // exit 0 today. Nothing here is turned OFF: every rule below still runs and
  // still reports on every file. They are demoted to `warn` so they do not
  // BLOCK, and `package.json`'s `--max-warnings <ceiling>` pins the count, so
  // the debt can only ever shrink. Lowering that ceiling as debt is paid is the
  // point; raising it needs a written reason in review.
  //
  // THE HARD GATE IS "0 ERRORS", NOT THE WARNING COUNT. ESLint exits non-zero
  // on any error whatever `--max-warnings` says, so every rule NOT demoted
  // below — including `react-hooks/rules-of-hooks` and everything in
  // `js.configs.recommended` — still blocks CI outright. That is the
  // regression check issue #442 asked for. The ceiling is the second-order
  // guard, and it is deliberately set ABOVE the current count so that ONE new
  // `any` in the untyped-JSON surface (or one newly-unused eslint-disable
  // directive) does not turn an unrelated commit red.
  //
  // This block is deliberately placed BEFORE overlay A: later blocks win, so a
  // trailing ratchet would re-enable (as warnings) the very rules overlay A
  // switches off for the vendored mapbox surface.
  //
  // Measured baselines at the time of the ESLint 9 flat-config migration
  // (`npx eslint src -f json`, 227 files):
  //   untyped-boundary family .............. 647
  //   floating / misused promises ........... 83
  //   react-hooks React Compiler rules ...... 29
  //   react-hooks/exhaustive-deps ........... 34   (never demoted here -- the
  //                                                 preset already warns)
  //   react-refresh/only-export-components ... 7
  // CURRENT COUNT: 799 warnings, 0 errors (2026-08-20, `yarn lint`, after
  // deleting the orphaned src/utils/ansi.ts). Ceiling pinned in package.json:
  // 900 — roughly 12% headroom, enough that ordinary work on the untyped-JSON
  // surface does not trip it, small enough that a bulk regression still does.
  //
  // It is a CEILING, not a target. RATCHET IT DOWN as debt is paid: after a
  // clean-up that removes a batch of warnings, re-run `yarn lint`, read the new
  // count off the summary line, update this comment, and lower the number in
  // package.json back to about count + 100. Raising it needs a written reason
  // in review.
  {
    files: ['**/*.{ts,tsx}'],
    rules: {
      // (1) Typing debt on the settings-schema / rosbridge-JSON surface. 647
      // findings across ~73 files, all of the same shape: JSON arrives as
      // `any` and flows on untyped. Paying this down means typing those
      // payloads, which is a refactor, not a lint fix.
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unsafe-assignment': 'warn',
      '@typescript-eslint/no-unsafe-member-access': 'warn',
      '@typescript-eslint/no-unsafe-call': 'warn',
      '@typescript-eslint/no-unsafe-argument': 'warn',
      '@typescript-eslint/no-unsafe-return': 'warn',

      // (2) Unhandled promise rejections, 83 sites over 37 files. The fast fix
      // -- prefixing `void` -- is the WRONG fix: it turns an unhandled
      // rejection into a silently swallowed one, which this repo's
      // error-handling rule forbids outright. Each site needs a real `.catch`
      // that surfaces through the notification centre, so they are tracked as
      // debt rather than papered over.
      '@typescript-eslint/no-floating-promises': 'warn',
      '@typescript-eslint/no-misused-promises': 'warn',

      // (3) React Compiler rules, new in eslint-plugin-react-hooks v7 and
      // never applied to this codebase before. 29 findings. Each is a genuine
      // render-phase ref read / effect-time setState, but "fixing" them
      // changes effect timing in map and settings hooks -- real behavioural
      // risk in a robot control UI, so they land as reported debt.
      // NOTE: `react-hooks/rules-of-hooks` is deliberately NOT in this list --
      // it stays an error.
      'react-hooks/refs': 'warn',
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/immutability': 'warn',
      'react-hooks/preserve-manual-memoization': 'warn',
      'react-hooks/purity': 'warn',
    },
  },

  // -- Overlay A -- vendored, untyped mapbox-gl-draw surface -----------------
  // `src/modes/*` are hand-ports of @mapbox/mapbox-gl-draw's INTERNAL JS modes
  // (`MapboxDraw.lib.*`, `const Mode: any = {}`), and
  // `src/types/mapbox-gl-draw.d.ts` is the hand-written ambient stub for that
  // library -- it ships no types of its own. Every violation of the rules below
  // is the same finding, "the vendored API surface is `any`", and the only way
  // to satisfy them is to type a third-party library this project deliberately
  // did not type. Together these two paths are 34% of all lint problems.
  //
  // REVIEWER NOTE: this must not become a dumping ground. If genuinely
  // first-party logic is ever added under `src/modes/`, these rules go silently
  // off for it -- move that logic out instead. `src/test/eslint-config.test.ts`
  // pins the boundary. Every non-type-aware rule and every react-hooks rule
  // stays ON here.
  {
    files: ['src/modes/**', 'src/types/mapbox-gl-draw.d.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/unbound-method': 'off',
    },
  },

  // -- Overlay B -- files that are not fast-refresh boundaries ---------------
  // `src/main.tsx` is the Vite entry module: it has zero exports and is mounted
  // via createRoot, so React Fast Refresh never treats it as a boundary. Test
  // files and test mocks are not shipped modules at all. The GENUINE
  // fast-refresh warnings elsewhere are deliberately left reported.
  {
    files: ['src/main.tsx', 'src/test/**', '**/*.test.ts', '**/*.test.tsx'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
]
