// Code generated by generate_go_msgs.sh — DO NOT EDIT.
package mowgli

import (
	"github.com/mowglinext/mowglinext/pkg/msgs/geometry"
)

// AddLidarIgnoreCorridorReq for mowgli_interfaces/srv/AddLidarIgnoreCorridor request.
type AddLidarIgnoreCorridorReq struct {
	Corridor                  LidarIgnoreCorridor            `json:"corridor"`
}

// AddLidarIgnoreCorridorRes for mowgli_interfaces/srv/AddLidarIgnoreCorridor response.
type AddLidarIgnoreCorridorRes struct {
	Success                   bool                           `json:"success"`
	Id                        uint32                         `json:"id"`
}

// AddMowingAreaReq for mowgli_interfaces/srv/AddMowingArea request.
type AddMowingAreaReq struct {
	Area                      MapArea                        `json:"area"`
	IsNavigationArea          bool                           `json:"is_navigation_area"`
}

// AddMowingAreaRes for mowgli_interfaces/srv/AddMowingArea response.
type AddMowingAreaRes struct {
	Success                   bool                           `json:"success"`
}

// AreaRecordingReq for mowgli_interfaces/srv/AreaRecording request.
type AreaRecordingReq struct {
	Command                   uint8                          `json:"command"`
	AreaName                  string                         `json:"area_name"`
	IsExclusionZone           bool                           `json:"is_exclusion_zone"`
}

// AreaRecordingRes for mowgli_interfaces/srv/AreaRecording response.
type AreaRecordingRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
	Polygon                   geometry.Polygon               `json:"polygon"`
}

// BladeControlReq for mowgli_interfaces/srv/BladeControl request.
type BladeControlReq struct {
	MowEnabled                uint8                          `json:"mow_enabled"`
	MowDirection              uint8                          `json:"mow_direction"`
}

// BladeControlRes for mowgli_interfaces/srv/BladeControl response.
type BladeControlRes struct {
	Success                   bool                           `json:"success"`
	Forwarded                 bool                           `json:"forwarded"`
	Message                   string                         `json:"message"`
}

// CalibrateImuYawReq for mowgli_interfaces/srv/CalibrateImuYaw request.
type CalibrateImuYawReq struct {
	DurationSec               float64                        `json:"duration_sec"`
	MagOnly                   bool                           `json:"mag_only"`
}

// CalibrateImuYawRes for mowgli_interfaces/srv/CalibrateImuYaw response.
type CalibrateImuYawRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
	ImuYawRad                 float64                        `json:"imu_yaw_rad"`
	ImuYawDeg                 float64                        `json:"imu_yaw_deg"`
	SamplesUsed               int32                          `json:"samples_used"`
	StdDevDeg                 float64                        `json:"std_dev_deg"`
	ImuPitchRad               float64                        `json:"imu_pitch_rad"`
	ImuPitchDeg               float64                        `json:"imu_pitch_deg"`
	ImuRollRad                float64                        `json:"imu_roll_rad"`
	ImuRollDeg                float64                        `json:"imu_roll_deg"`
	StationarySamplesUsed     int32                          `json:"stationary_samples_used"`
	GravityMagMps2            float64                        `json:"gravity_mag_mps2"`
	DockValid                 bool                           `json:"dock_valid"`
	DockPoseX                 float64                        `json:"dock_pose_x"`
	DockPoseY                 float64                        `json:"dock_pose_y"`
	DockPoseYawRad            float64                        `json:"dock_pose_yaw_rad"`
	DockPoseYawDeg            float64                        `json:"dock_pose_yaw_deg"`
	DockYawSigmaDeg           float64                        `json:"dock_yaw_sigma_deg"`
	DockUndockDisplacementM   float64                        `json:"dock_undock_displacement_m"`
}

// ClearLidarIgnoreCorridorsReq for mowgli_interfaces/srv/ClearLidarIgnoreCorridors request (empty).
type ClearLidarIgnoreCorridorsReq struct{}

// ClearLidarIgnoreCorridorsRes for mowgli_interfaces/srv/ClearLidarIgnoreCorridors response.
type ClearLidarIgnoreCorridorsRes struct {
	Success                   bool                           `json:"success"`
}

// ClearMapReq for mowgli_interfaces/srv/ClearMap request (empty).
type ClearMapReq struct{}

// ClearMapRes for mowgli_interfaces/srv/ClearMap response.
type ClearMapRes struct {
	Success                   bool                           `json:"success"`
}

// ClearObstacleReq for mowgli_interfaces/srv/ClearObstacle request.
type ClearObstacleReq struct {
	ObstacleId                uint32                         `json:"obstacle_id"`
}

// ClearObstacleRes for mowgli_interfaces/srv/ClearObstacle response.
type ClearObstacleRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
}

// CorrectRecordedObstacleReq for mowgli_interfaces/srv/CorrectRecordedObstacle request.
type CorrectRecordedObstacleReq struct {
	Polygon                   geometry.Polygon               `json:"polygon"`
}

// CorrectRecordedObstacleRes for mowgli_interfaces/srv/CorrectRecordedObstacle response.
type CorrectRecordedObstacleRes struct {
	Corrected                 geometry.Polygon               `json:"corrected"`
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
}

// CoverageOrientationReq for mowgli_interfaces/srv/CoverageOrientation request.
type CoverageOrientationReq struct {
	AreaIndex                 uint32                         `json:"area_index"`
	SetNext                   bool                           `json:"set_next"`
	Perpendicular             bool                           `json:"perpendicular"`
}

// CoverageOrientationRes for mowgli_interfaces/srv/CoverageOrientation response.
type CoverageOrientationRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
	Enabled                   bool                           `json:"enabled"`
	CurrentActive             bool                           `json:"current_active"`
	CurrentPerpendicular      bool                           `json:"current_perpendicular"`
	NextPerpendicular         bool                           `json:"next_perpendicular"`
	BaseAngleDeg              float64                        `json:"base_angle_deg"`
}

// EmergencyStopReq for mowgli_interfaces/srv/EmergencyStop request.
type EmergencyStopReq struct {
	Emergency                 uint8                          `json:"emergency"`
}

// EmergencyStopRes for mowgli_interfaces/srv/EmergencyStop response.
type EmergencyStopRes struct {
	Success                   bool                           `json:"success"`
}

// GetLidarIgnoreCorridorsReq for mowgli_interfaces/srv/GetLidarIgnoreCorridors request (empty).
type GetLidarIgnoreCorridorsReq struct{}

// GetLidarIgnoreCorridorsRes for mowgli_interfaces/srv/GetLidarIgnoreCorridors response.
type GetLidarIgnoreCorridorsRes struct {
	Corridors                 []LidarIgnoreCorridor          `json:"corridors"`
	Success                   bool                           `json:"success"`
}

// GetMowingAreaReq for mowgli_interfaces/srv/GetMowingArea request.
type GetMowingAreaReq struct {
	Index                     uint32                         `json:"index"`
}

// GetMowingAreaRes for mowgli_interfaces/srv/GetMowingArea response.
type GetMowingAreaRes struct {
	Area                      MapArea                        `json:"area"`
	Success                   bool                           `json:"success"`
}

// GetRecoveryPointReq for mowgli_interfaces/srv/GetRecoveryPoint request (empty).
type GetRecoveryPointReq struct{}

// GetRecoveryPointRes for mowgli_interfaces/srv/GetRecoveryPoint response.
type GetRecoveryPointRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
	RecoveryPose              geometry.Pose                  `json:"recovery_pose"`
	DistanceOutside           float64                        `json:"distance_outside"`
}

// HighLevelControlReq for mowgli_interfaces/srv/HighLevelControl request.
type HighLevelControlReq struct {
	Command                   uint8                          `json:"command"`
}

// HighLevelControlRes for mowgli_interfaces/srv/HighLevelControl response.
type HighLevelControlRes struct {
	Success                   bool                           `json:"success"`
}

// MowerControlReq for mowgli_interfaces/srv/MowerControl request.
type MowerControlReq struct {
	MowEnabled                uint8                          `json:"mow_enabled"`
	MowDirection              uint8                          `json:"mow_direction"`
}

// MowerControlRes for mowgli_interfaces/srv/MowerControl response.
type MowerControlRes struct {
	Success                   bool                           `json:"success"`
}

// PreviewCoverageReq for mowgli_interfaces/srv/PreviewCoverage request.
type PreviewCoverageReq struct {
	OuterBoundary             geometry.Polygon               `json:"outer_boundary"`
	Obstacles                 []geometry.Polygon             `json:"obstacles"`
	MowAngleDeg               float64                        `json:"mow_angle_deg"`
	Perpendicular             bool                           `json:"perpendicular"`
	RingDirection             int32                          `json:"ring_direction"`
	HasStartPoint             bool                           `json:"has_start_point"`
	StartX                    float64                        `json:"start_x"`
	StartY                    float64                        `json:"start_y"`
}

// PreviewCoverageRes for mowgli_interfaces/srv/PreviewCoverage response.
type PreviewCoverageRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
	Rings                     []geometry.Polygon             `json:"rings"`
	Swaths                    []geometry.Polygon             `json:"swaths"`
	MowAngleDeg               float64                        `json:"mow_angle_deg"`
	HeadlandPasses            int32                          `json:"headland_passes"`
	RingDirection             int32                          `json:"ring_direction"`
	PlannedFraction           float64                        `json:"planned_fraction"`
	FieldAreaM2               float64                        `json:"field_area_m2"`
	DroppedPieces             uint32                         `json:"dropped_pieces"`
	StartAdjustable           bool                           `json:"start_adjustable"`
	StartX                    float64                        `json:"start_x"`
	StartY                    float64                        `json:"start_y"`
}

// PreviewObstacleClearanceReq for mowgli_interfaces/srv/PreviewObstacleClearance request.
type PreviewObstacleClearanceReq struct {
	Obstacles                 []geometry.Polygon             `json:"obstacles"`
}

// PreviewObstacleClearanceRes for mowgli_interfaces/srv/PreviewObstacleClearance response.
type PreviewObstacleClearanceRes struct {
	Buffered                  []geometry.Polygon             `json:"buffered"`
	ObstacleMarginM           float64                        `json:"obstacle_margin_m"`
}

// PromoteObstacleReq for mowgli_interfaces/srv/PromoteObstacle request.
type PromoteObstacleReq struct {
	AreaIndex                 uint32                         `json:"area_index"`
	ObstacleId                uint32                         `json:"obstacle_id"`
	Polygon                   geometry.Polygon               `json:"polygon"`
	PendingId                 uint32                         `json:"pending_id"`
	Name                      string                         `json:"name"`
}

// PromoteObstacleRes for mowgli_interfaces/srv/PromoteObstacle response.
type PromoteObstacleRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
}

// SetAreaCoverageLinesReq for mowgli_interfaces/srv/SetAreaCoverageLines request.
type SetAreaCoverageLinesReq struct {
	Id                        uint32                         `json:"id"`
	HasMowAngle               bool                           `json:"has_mow_angle"`
	MowAngleDeg               float64                        `json:"mow_angle_deg"`
	HasRingDirection          bool                           `json:"has_ring_direction"`
	RingDirection             uint8                          `json:"ring_direction"`
	HasStartPoint             bool                           `json:"has_start_point"`
	StartX                    float64                        `json:"start_x"`
	StartY                    float64                        `json:"start_y"`
}

// SetAreaCoverageLinesRes for mowgli_interfaces/srv/SetAreaCoverageLines response.
type SetAreaCoverageLinesRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
}

// SetDockingPointReq for mowgli_interfaces/srv/SetDockingPoint request.
type SetDockingPointReq struct {
	DockingPose               geometry.Pose                  `json:"docking_pose"`
	UseGpsPosition            bool                           `json:"use_gps_position"`
	YawSource                 uint8                          `json:"yaw_source"`
	YawRad                    float64                        `json:"yaw_rad"`
	PreservePosition          bool                           `json:"preserve_position"`
	UsePendingAntenna         bool                           `json:"use_pending_antenna"`
}

// SetDockingPointRes for mowgli_interfaces/srv/SetDockingPoint response.
type SetDockingPointRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
	StoredPose                geometry.Pose                  `json:"stored_pose"`
}

// SetFleetAssignmentReq for mowgli_interfaces/srv/SetFleetAssignment request.
type SetFleetAssignmentReq struct {
	ExcludedAreas             []uint32                       `json:"excluded_areas"`
	PreferredStartIndex       int32                          `json:"preferred_start_index"`
	Reason                    string                         `json:"reason"`
}

// SetFleetAssignmentRes for mowgli_interfaces/srv/SetFleetAssignment response.
type SetFleetAssignmentRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
}

// StartInAreaReq for mowgli_interfaces/srv/StartInArea request.
type StartInAreaReq struct {
	Area                      uint8                          `json:"area"`
}

// StartInAreaRes for mowgli_interfaces/srv/StartInArea response.
type StartInAreaRes struct {
	Success                   bool                           `json:"success"`
}

// TriggerReplanReq for mowgli_interfaces/srv/TriggerReplan request.
type TriggerReplanReq struct {
	Reason                    string                         `json:"reason"`
}

// TriggerReplanRes for mowgli_interfaces/srv/TriggerReplan response.
type TriggerReplanRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
}

