// Code generated by generate_go_msgs.sh — DO NOT EDIT.
package mowgli

import (
	"github.com/mowglinext/mowglinext/pkg/msgs/geometry"
)

// AddMowingAreaReq for mowgli_interfaces/srv/AddMowingArea request.
type AddMowingAreaReq struct {
	Area                      MapArea                        `json:"area"`
	IsNavigationArea          bool                           `json:"is_navigation_area"`
}

// AddMowingAreaRes for mowgli_interfaces/srv/AddMowingArea response.
type AddMowingAreaRes struct {
	Success                   bool                           `json:"success"`
}

// AreaRecordingReq for mowgli_interfaces/srv/AreaRecording request.
type AreaRecordingReq struct {
	Command                   uint8                          `json:"command"`
	AreaName                  string                         `json:"area_name"`
	IsExclusionZone           bool                           `json:"is_exclusion_zone"`
}

// AreaRecordingRes for mowgli_interfaces/srv/AreaRecording response.
type AreaRecordingRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
	Polygon                   geometry.Polygon               `json:"polygon"`
}

// CalibrateImuYawReq for mowgli_interfaces/srv/CalibrateImuYaw request.
type CalibrateImuYawReq struct {
	DurationSec               float64                        `json:"duration_sec"`
	MagOnly                   bool                           `json:"mag_only"`
}

// CalibrateImuYawRes for mowgli_interfaces/srv/CalibrateImuYaw response.
type CalibrateImuYawRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
	ImuYawRad                 float64                        `json:"imu_yaw_rad"`
	ImuYawDeg                 float64                        `json:"imu_yaw_deg"`
	SamplesUsed               int32                          `json:"samples_used"`
	StdDevDeg                 float64                        `json:"std_dev_deg"`
	ImuPitchRad               float64                        `json:"imu_pitch_rad"`
	ImuPitchDeg               float64                        `json:"imu_pitch_deg"`
	ImuRollRad                float64                        `json:"imu_roll_rad"`
	ImuRollDeg                float64                        `json:"imu_roll_deg"`
	StationarySamplesUsed     int32                          `json:"stationary_samples_used"`
	GravityMagMps2            float64                        `json:"gravity_mag_mps2"`
	DockValid                 bool                           `json:"dock_valid"`
	DockPoseX                 float64                        `json:"dock_pose_x"`
	DockPoseY                 float64                        `json:"dock_pose_y"`
	DockPoseYawRad            float64                        `json:"dock_pose_yaw_rad"`
	DockPoseYawDeg            float64                        `json:"dock_pose_yaw_deg"`
	DockYawSigmaDeg           float64                        `json:"dock_yaw_sigma_deg"`
	DockUndockDisplacementM   float64                        `json:"dock_undock_displacement_m"`
}

// ClearMapReq for mowgli_interfaces/srv/ClearMap request (empty).
type ClearMapReq struct{}

// ClearMapRes for mowgli_interfaces/srv/ClearMap response.
type ClearMapRes struct {
	Success                   bool                           `json:"success"`
}

// ClearObstacleReq for mowgli_interfaces/srv/ClearObstacle request.
type ClearObstacleReq struct {
	ObstacleId                uint32                         `json:"obstacle_id"`
}

// ClearObstacleRes for mowgli_interfaces/srv/ClearObstacle response.
type ClearObstacleRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
}

// EmergencyStopReq for mowgli_interfaces/srv/EmergencyStop request.
type EmergencyStopReq struct {
	Emergency                 uint8                          `json:"emergency"`
}

// EmergencyStopRes for mowgli_interfaces/srv/EmergencyStop response.
type EmergencyStopRes struct {
	Success                   bool                           `json:"success"`
}

// GetMowingAreaReq for mowgli_interfaces/srv/GetMowingArea request.
type GetMowingAreaReq struct {
	Index                     uint32                         `json:"index"`
}

// GetMowingAreaRes for mowgli_interfaces/srv/GetMowingArea response.
type GetMowingAreaRes struct {
	Area                      MapArea                        `json:"area"`
	Success                   bool                           `json:"success"`
}

// GetRecoveryPointReq for mowgli_interfaces/srv/GetRecoveryPoint request (empty).
type GetRecoveryPointReq struct{}

// GetRecoveryPointRes for mowgli_interfaces/srv/GetRecoveryPoint response.
type GetRecoveryPointRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
	RecoveryPose              geometry.Pose                  `json:"recovery_pose"`
	DistanceOutside           float64                        `json:"distance_outside"`
}

// HighLevelControlReq for mowgli_interfaces/srv/HighLevelControl request.
type HighLevelControlReq struct {
	Command                   uint8                          `json:"command"`
}

// HighLevelControlRes for mowgli_interfaces/srv/HighLevelControl response.
type HighLevelControlRes struct {
	Success                   bool                           `json:"success"`
}

// MowerControlReq for mowgli_interfaces/srv/MowerControl request.
type MowerControlReq struct {
	MowEnabled                uint8                          `json:"mow_enabled"`
	MowDirection              uint8                          `json:"mow_direction"`
}

// MowerControlRes for mowgli_interfaces/srv/MowerControl response.
type MowerControlRes struct {
	Success                   bool                           `json:"success"`
}

// PromoteObstacleReq for mowgli_interfaces/srv/PromoteObstacle request.
type PromoteObstacleReq struct {
	AreaIndex                 uint32                         `json:"area_index"`
	ObstacleId                uint32                         `json:"obstacle_id"`
	Polygon                   geometry.Polygon               `json:"polygon"`
	PendingId                 uint32                         `json:"pending_id"`
	Name                      string                         `json:"name"`
}

// PromoteObstacleRes for mowgli_interfaces/srv/PromoteObstacle response.
type PromoteObstacleRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
}

// SetDockingPointReq for mowgli_interfaces/srv/SetDockingPoint request.
type SetDockingPointReq struct {
	DockingPose               geometry.Pose                  `json:"docking_pose"`
	UseGpsPosition            bool                           `json:"use_gps_position"`
	YawSource                 uint8                          `json:"yaw_source"`
	YawRad                    float64                        `json:"yaw_rad"`
}

// SetDockingPointRes for mowgli_interfaces/srv/SetDockingPoint response.
type SetDockingPointRes struct {
	Success                   bool                           `json:"success"`
}

// StartInAreaReq for mowgli_interfaces/srv/StartInArea request.
type StartInAreaReq struct {
	Area                      uint8                          `json:"area"`
}

// StartInAreaRes for mowgli_interfaces/srv/StartInArea response.
type StartInAreaRes struct {
	Success                   bool                           `json:"success"`
}

// TriggerReplanReq for mowgli_interfaces/srv/TriggerReplan request.
type TriggerReplanReq struct {
	Reason                    string                         `json:"reason"`
}

// TriggerReplanRes for mowgli_interfaces/srv/TriggerReplan response.
type TriggerReplanRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
}

